### ISSUE TITLE
Move from astropy to CCL in ShearAzimuthalAverager

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#103]
ShearAzimuthalAverager requires some cosmology to convert angular distances to physical Mpc. At the moment Astropy is used for that purpose. The code should be changed to use CCL instead. 

Also, cosmology should be passed as an (optional) argument to ShearAzimuthalAverager instead of being hard-coded, as is currently the case.

**Comment by m-aguena** [comment]
This is being covered by #114
