### ISSUE TITLE
Choosing Dependency Versions

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#106]
In issue #104, we had not specified a version for sphinx. This resulted in travis installing the most recent version which was not compatible with our code, causing travis to fail. My suggestion moving forward is to

1. Manually set the version of each dependency in `requirements.txt`, `.travis.yml`, `setup.py`, `docs/rtd-requirements.txt`. We should set the current, most up-to-date version of each dependency manually to avoid future bugs.

2. Set ourselves up such that travis runs both at our specific versions and at the most up to date versions. This will allow us to immediately see if a problem is caused by a dependency update. We can then fix this in the future if we want but still have reliably have running code at our supported versions.

**Comment by aimalz** [comment]
Nice job with #105 @matthewkirby!
