### ISSUE TITLE
Refactor model definition

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#111]

**Comment by combet** [comment]
Bochum retreat. New sets of functions based on cluster-toolkit and CCL to produce theoretical models of radial profiles.

**Comment by aimalz** [comment]
[This comment](https://github.com/LSSTDESC/CLMM/issues/16#issuecomment-432668122) by @cristobal-sifon almost got lost in #16, but it's relevant here, so I'm repeating it.

**Comment by cavestruz** [comment]
![image](https://user-images.githubusercontent.com/4805499/61594000-adcf0780-abb4-11e9-805d-62489946b481.png)

**Comment by cavestruz** [comment]
To do still:
- clearer docstrings with latex of lensing model profile relationships
- correct the units, so test profiles look reasonable 
- decide on a bunch of methods in a .py file vs having these as methods in a class

**Comment by cavestruz** [comment]
Note - at the tag-up this morning, we decided to have a bunch of methods in a .py file.   Currently, that .py file is called profilepredicting.py

**Comment by cavestruz** [comment]
Note - docstrings are all filled in now, but we'll need to later check how it renders in sphinx and if it's to our liking.

**Comment by cavestruz** [comment]
Units should be all good - profile plots look reasonable!

**Comment by aimalz** [comment]
#121 is probably a prerequisite to this issue.

**Comment by combet** [comment]
Also to do:
- [] fix the omega_m function. CCL cosmology objects are immutable. Cannot add an Omega_m attribute
