### ISSUE TITLE
Re-write/replace ShearAzimuthalAverager 

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#114]
https://github.com/LSSTDESC/CLMM/blob/issue/114/rewrite_shear_azimuthl_averager/examples/rewrite_shearAzimuthalAverager.ipynb

https://nbviewer.jupyter.org/

**Comment by marina-ricci** [comment]
- [ ]  update the docstrings

**Comment by lbaumo** [comment]
replace tangential shear function with a function that computes theta and phi, then a function that computes gt, then a function that computes g_x

**Comment by aimalz** [comment]
Next steps (with help from the #110 crew once #113 is resolved): 
- [ ] move the notebook content into modules
- [ ] wrap the functions in the `GalaxyCluster` object
- [ ] write tests

**Comment by aimalz** [comment]
- [ ] Remove data file and use mock data in demo

**Comment by matthewkirby** [comment]
I am going to close this issue since we have now merged PR #143. There are still some small things to be cleaned up but I have added them to other issues.
