### ISSUE TITLE
Updating README and CONTRIBUTING

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#115]
Currently, we have a README.md, clmm/README.md, and CONTRIBUTING.md. These are wildly outdated. 

This issue can be closed when
- [x] README.md has been updated and revised
- [x] CONTRIBUTING.md has been updated and revised. Include instructions for testing docs. (make clean, make html, `open _build/html/index.html`)
- [x] clmm/README.md has been updated and revised
- [ ] Content from Issue #19 has been included in CONTRIBUTING.md
- [ ] Set these pages to compile into docs for sphinx (is this doable?)
- [x] Instructions for opening a development issue (checklist, more?)

**Comment by matthewkirby** [comment]
<img width="732" alt="summary" src="https://user-images.githubusercontent.com/5395125/61617248-96eaec80-ac6a-11e9-8cfa-4594247f1e26.png">

**Comment by aimalz** [comment]
Let's make the readme and contributing have the style of [CCL's](https://github.com/LSSTDESC/CCL).

**Comment by aimalz** [comment]
I think we finished this but forgot to close the issue.
