### ISSUE TITLE
Setup travis to install CCL and cluster_toolkit

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#120]
This issue can be closed when:

- [ ] Travis runs a simple import test after installing CCL.
- [x] Travis runs cluster_toolkit

**Comment by matthewkirby** [comment]
This is being pushed away from minimal example. For now, we are running with astropy until we are able to more reliably install CCL.

**Comment by lbaumo** [comment]
I just realized I can use gcc 5 at slac, so I can let you know if it allows clusertoolkit to install

**Comment by lbaumo** [comment]
okay, compiling with gcc 5 gives errors, so I would use 6 and higher to be safe

**Comment by matthewkirby** [comment]
Great thanks for checking! At this point, gcc 6 or 7 or something is
installed. It’s just a matter of telling the cluster toolkit installer to
use the right install. Locally, I did this with os.environ[‘CC’]=‘gcc-9’
directly into the setup.py but we can’t do it that way on Travis.

**Comment by aimalz** [comment]
Just leaving a comment to say #148 resolved the issue with cluster-toolkit.  I'm going to remove the priority tag for now because our tests have workarounds for CCL right now.

**Comment by aimalz** [comment]
Now that CCL is pip/conda-installable, we can do a quick test to see if this issue can be quickly resolved.

**Comment by combet** [comment]
Fixed in PR #299
