### ISSUE TITLE
Astropy-CCL patch

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#121]
Due to widespread CCL/NERSC bugs, we need to have a temporary workaround that will let us test our code, connect our data and theory operations, and get Travis running again.  In `profilepredicting.py`, we can wrap the following functions so that they use the astropy function if CCL is not available, and then the rest of the functions in the module will call our wrapped version.
- [x] ccl.physical_constants.CLIGHT in `get_critical_surface_density()`
- [x] ccl.physical_constants.GNEWT in `get_critical_surface_density()`
- [x] ccl.comoving_angular_distance in `get_critical_surface_density()`

**Comment by cavestruz** [comment]
[] Helper function to convert from an astropy cosmology object to a ccl looking object (e.g. from attributes to a dictionary)

**Comment by aimalz** [comment]
This has now been taken care of in the branch for #111.  Thanks @shenmingfu @combet @cavestruz!
