### ISSUE TITLE
Future discussion points

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#122]
This issue can just be a checklist of discussions that we are postponing till later. As PRs come in, I can add things to this checklist by looking at inline comments referencing unresolved discussions. Resolve these issues after the Bochum workshop

- Should we allow GalaxyCluster.unique_id to be a float? We would then int() but this could be dangerous if a user supplies a bunch of float ids for some reason. (Should likely be int)
- Should we use manual typing? https://docs.python.org/3/library/typing.html (EXTENSION)
- [x] polaraveraging.py readdress some of the docstrings where noted.
- [x] Patching functions to classes is currently in the __init__.py. Can we move this to the files containing the functions?
- [x] Change import behavior?
- [x] astropy version > 3 at least. 2.0.2 doesn't 
work (3.2.1 works for me)
##Marina added :
- [x] should we create a "utils.py" file with function shared by data and modelling? 
- [x] find a best way to manipulate shear profiles than attaching them to cluster object
- [ ] attach cosmology, units and bin definition to the profile tables

**Comment by cavestruz** [comment]
For first two checkmarks, @combet and I thought the int was something we should be able to expect for the ids.  And for the manual typing, this would be a future extension if we decided to do this.  The profile table metadata is now its own issue #259.
