### ISSUE TITLE
Create notebook to test the impact of cluster miscentering

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#129]
This issue can be closed when there's a notebook using clmm to try out different miscentering distributions to see how it affects the mass estimate.

**Comment by cavestruz** [comment]
- [ ] Write a minimal very simple miscentering algorithm for "new" ra, dec assigments
- [ ] Read in a mock galaxy cluster, and get M_wl distribution for a given miscentering distribution
