### ISSUE TITLE
Notebook for cluster mass via color cut method

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#130]
This will implement the color cut method (see WtGIII) for mass reconstruction, i.e. when we don't know the individual redshift of the galaxies. This will require implementing the "beta + shear at infinity" description for the shear/convergence.

**Comment by cavestruz** [comment]
- [ ] Beta_s function from integrating distribution of redshifts in a source redshift bin.
- [ ] Beta_s2 function from integrating distribution of redshifts in a source redshift bin.

**Comment by marina-ricci** [comment]
@combet : this should be feasible now that the beta and beta_s2 function are implemented.

**Comment by combet** [comment]
@marina-ricci, yes it does! I'm closing this issue.
