### ISSUE TITLE
Incorporate cluster_toolkit as a submodule/subproject of CCL

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#144]
CLMM should only have a dependency on CCL, but it currently depends on [cluster_toolkit](https://github.com/tmcclintock/cluster_toolkit), which is ultimately destined for integration into CCL.  **This is a high-priority task without an asignee.**  If anyone in this repository wants to get involved in CCL, please leave a comment on LSSTDESC/CCL#291 and in this issue.

**Comment by pennalima** [comment]
Hi @aimalz, I can do this.

**Comment by aimalz** [comment]
@c-d-leonard [has notified us](https://github.com/LSSTDESC/CCL/issues/291#issuecomment-577460285) that CCL now has some support for halo modeling.  Have we tested whether our current dependence on cluster\_toolkit can be replaced by that?  If CCL's new additions suffice, then we can have an option to use CCL's functionality instead of cluster\_toolkit when using CCL as the back-end.  Otherwise, I guess we should continue pursuing the plan of making a CCL submodule based on cluster\_toolkit.
