### ISSUE TITLE
Including shape noise in mock data can result in e1/e2 outside of physical domain

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#149]
Currently, mock_data.py does not check that e1 and e2 are in [-1,1]. This can become problematic when adding a random gaussian shape noise to the mock data, if the requested shape noise dispersion is too large.

**Comment by matthewkirby** [comment]
This was addressed and merged in PR #151. The PR addressed both issues 149 and 150 however this issue was never marked as resolved.
