### ISSUE TITLE
Small Revisions Before Release

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#152]
Hey so I have noticed some tiny things that aren't worth their own PR just yet. I figured rather than track them in a notes window I should open an issue! As we work towards a 1.0 release, lets keep track of these small things that don't fit in with other PRs. Then, just before we tag a release, we can PR all these small things at once under this issue.

`setup.py`
- [x] Duplicate imports
- [x] Wrong license listed
- [x] `classifiers` is just copied from somewhere and the are not applicable
- [x] `install_requires` field should just read from `requirements.txt` or equivalent
- [x] Issue #65: Status of GCData object
- [x] Delete crypt directories both in code and tests.
- [x] Delete --ignore in .travis.yml, setup.py, and docs/conf.py
- [x] Homogenize how we import our own functions from other modules. Should be done like `from .galaxycluster import GalaxyCluster`
- [x] Add instructions to run linter to contributing.md (both on code and on notebooks)

**Comment by m-aguena** [comment]
Other minor fixes I noted:

- [ ] make sure the parameters defined in cell 4 of the modelling_demo notebook are being passed to the functions, some of them have the values written again in function calls and some are using default implicit args

- [ ] `det_3d_density` has `z_src_model` as a parameter in the docstring, which makes no sense

- [ ] `\Xi` in `predict_surface_density` is the halo matter correlation not the halo mass function

**Comment by aimalz** [comment]
I think #170 is also part of this.

**Comment by aimalz** [comment]
Also, @matthewkirby is it now possible to include `cluster_toolkit` and `CCL` in `requirements.txt`?  If so, we might want to add that to this list.

**Comment by matthewkirby** [comment]
To run a linter on jupyter notebooks,

1. Install packages (i don't think flake8 is actually needed)
`pip install flake8 pycodestyle_magic`

2. Put a new cell at the top of the notebook and put these two magics into it and run.
```
%load_ext pycodestyle_magic
%pycodestyle_on
```

**Comment by matthewkirby** [comment]
> Also, @matthewkirby is it now possible to include `cluster_toolkit` and `CCL` in `requirements.txt`? If so, we might want to add that to this list.

Issue #120 deals with CCL. Rumor has it that it is now pip installable which means we could install it that way. If we did, we would be able to use the basic cosmology calculations from CCL which would be great.

However, we also want the halo code from CCL. This currently exists in an open PR (https://github.com/LSSTDESC/CCL/pull/704). Once this is merged, we will likely want to use this over clustertoolkit. Unless CCL does a release right after this is merged, we will need to install CCL via cloning the repo at a specific point (until the halo code is included in a release).

**Comment by cristobal-sifon** [comment]
- [ ] The text introducing cell 9 in ``demo_generate_mock_cluster.ipynb``  says "all galaxies at the same redshift" but the function receives `'chang13'` as the ``src_z`` argument. Given the order of cells I think this should have a single redshift, rather than change the text

**Comment by cavestruz** [comment]
@m-aguena , you may have seen the slack chat comment:

> @here - @combet and I are looking through outstanding issues in the code.  One bit that we wanted to touch base with the group on is a point in issue #152 and the use of cclify_astropy_cosmo in the demo_modelling notebook (cell 4)
modeling.py can take both ccl cosmology objects and astropy objects (through cclify_astropy_cosmo)
utils.py and others request and astropy object
The main reason for using astropy back in Bochum was because ccl did not compute the angular diameter distance wrt to z1 and z2 (as opposed to 0 to z), and astropy did.  We should keep things consistent - should we just keep things in astropy, and not use cclify_astropy_cosmo for v1.0?  Or should we aim to have other parts of the code also accept a ccl cosmology object?

But, this is what your outstanding point is referring to, yes?

> make sure the parameters defined in cell 4 of the modelling_demo notebook are being passed to the functions, some of them have the values written again in function calls and some are using default implicit args

**Comment by m-aguena** [comment]
> @m-aguena , you may have seen the slack chat comment:
> 
> > @here - @combet and I are looking through outstanding issues in the code.  One bit that we wanted to touch base with the group on is a point in issue #152 and the use of cclify_astropy_cosmo in the demo_modelling notebook (cell 4)
> > modeling.py can take both ccl cosmology objects and astropy objects (through cclify_astropy_cosmo)
> > utils.py and others request and astropy object
> > The main reason for using astropy back in Bochum was because ccl did not compute the angular diameter distance wrt to z1 and z2 (as opposed to 0 to z), and astropy did.  We should keep things consistent - should we just keep things in astropy, and not use cclify_astropy_cosmo for v1.0?  Or should we aim to have other parts of the code also accept a ccl cosmology object?
> 
> But, this is what your outstanding point is referring to, yes?
> 
> > make sure the parameters defined in cell 4 of the modelling_demo notebook are being passed to the functions, some of them have the values written again in function calls and some are using default implicit args

@cavestruz Not really. Previous notebooks were kind of messy, where a certain quantity was passed to a variable (like `Delta` for example) but instead of passing that variable to function calls, an explicit number was written. This does not seem to be the case in the current notebooks though. I can cross this item.
