### ISSUE TITLE
Flesh out the docs with user-oriented introductory material

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#155]
In addition to API documentation that is automatically compiled from the docstrings, we should have solid documentation on how to use our code. For instance, see the "Getting Started" section on cluster toolkit's documentation (https://cluster-toolkit.readthedocs.io/en/latest/). These were manually written tutorials on how to use the code (you can take a look in the cluster toolkit git repo).

For comparison, we have 2 pages in our documentation, https://clmm.readthedocs.io/en/master/index.html. Installation and Citing, both of which are blank.

- [x] Provide comprehensive installation instructions including dependencies
- [x] Provide instructions for citing the code
- [x] Provide tutorials to use the code

To make these pages and have them appear in the docs, you need to write a the page and put it into the `docs/source/` directory. Just like docstrings, these files should be written in restructedtext. Additionally, to appear in the table of contents on the main page of our docs, it should be added to `docs/index.rst`

**Comment by aimalz** [comment]
Note: #115 includes the first two checklist items.

**Comment by aimalz** [comment]
This might also be a good place for changing the names of the demo notebooks to some kind of consistent format.

**Comment by aimalz** [comment]
@cavestruz I think what we want to do is add more `.rst` files into `CLMM/docs/source` and update the `CLMM/docs/index.rst` to match.
