### ISSUE TITLE
Sign problem in gamma_x (cross shear) definition?

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#157]
The cross shear is coded up as `gamma_x = - shear1 * np.sin(2.*phi) + shear2 * np.cos(2.*phi)`, but from g_t = -Re(g exp(-2i phi)) and g_x = -Im(g exp(-2i phi)), one gets reversed signs, i.e. `gamma_x = shear1 * np.sin(2.*phi) - shear2 * np.cos(2.*phi)`.

This should be double checked, confirmed and if so corrected. The tangential shear`gamma_t` appears to be coded OK. This happens in `polaraveraging.py` but should be checked for throughout the code.

Suggest doing so once PR 143 is processed.

**Comment by shenmingfu** [comment]
The formulas `g_t = -Re(g exp(-2i phi))` and `g_x = -Im(g exp(-2i phi))` are correct. 
Reference: [Schneider, 2006] Schneider, P. (2006). Weak gravitational lensing. Gravitational lensing: strong, weak and micro, pages 269–451.
Arxiv: https://arxiv.org/abs/astro-ph/0509252
Then new formula `gamma_x = shear1 * np.sin(2.*phi) - shear2 * np.cos(2.*phi)` is correct.

**Comment by shenmingfu** [comment]
The notebook I used for calculating `g_x` is `issue/114: demo_of_polaraveraging`, and it's using `import clmm.polaraveraging as pa`. In `pa`, the code uses `pa.compute_shear` and `pa.make_shear_profile` to get `g_x`.

**Comment by shenmingfu** [comment]
`pa.compute_shear` uses `def _compute_cross_shear(shear1, shear2, phi):` to get g_x. https://github.com/LSSTDESC/CLMM/blob/b49f247158e9826d9e9f077edc6b7e524f47e2be/clmm/polaraveraging.py#L199

**Comment by shenmingfu** [comment]
I realized the reason we had this sign issue is probably the definition of the direction of RA (and the definition of position angle phi) on the observation image and catalog. Now we use **RA from right to left**, but the position angle **phi is measured from x-axis (left to right) counter-clockwise**.
