### ISSUE TITLE
Fix z=0 limitation f functions that use cluster_toolkit

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#160]
`cluster_toolkit` is only setup to make computations at `z=0`, therefore many of our functions that use it (such as the nfw profile, sigma, etc) were set up not to use redshift in the computation. Our nfw profile (and all consequent computations) in `modeling` do not make sense for clusters at `z!=0`. This can be patched directly in `clmm` and still keep using `cluster_toolkit`

**Comment by matthewkirby** [comment]
Patched in PR #163 and merged into master. Once we move away from clustertoolkit it will be 100% resolved.
