### ISSUE TITLE
Make sure unit tests also validate with external values

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#162]
There are some (a lot) of unit tests of our functions that are only performing consistency checks (i. e. only checking results against themselves). We have to also check against known values.

**Comment by m-aguena** [comment]
Has to be fixed in
- [ ]  `modeling.py`

**Comment by aimalz** [comment]
Is this distinct from #158?

**Comment by m-aguena** [comment]
Solved by PR #200
