### ISSUE TITLE
Incomplete testing for functions in polaraveraging.py and utils.py

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#164]
We wish to merge PR #143 to allow for the end to end pipeline in the master branch. Currently, the code in this branch is not sufficiently tested. We are going to comment out incomplete tests, merge into master, and open this issue that will need to be resolved before a 1.0 release.

Tests for polaraveraging.py
===
1. There are many tests commented out. Why? Are they not needed, irrelevant, superfluous? If so lets just remove them. Is it because they are failing? If they failed when they weren't supposed to they are doing their job! We should ensure that we have no tests commented out and that we are AT A MINIMUM testing that if we give the function x, y, z we get the correct f(x,y,z) (for any set of options).
2. We should have tests that test every function. At the minimum, this could just be we pass the function x,y,z and compare f(x,y,z) to a truth. This truth could be computed on a piece of paper for many things or could be an output from a well-understood and validated software package.

- [x] Resolve commented tests in `tests/test_polaraveraging.py`
- [x] Make sure we are testing that each function works correctly.

**Comment by matthewkirby** [comment]
In the end, in PR #143 I ended up doing the first comment and `utils.py` should be taken care of (both the code and the tests). The only remaining thing to do here is clean up the tests in `test_polaraveraging.py`. For now, I expect that we do not need to worry about this. Before v1.0 we will need to do an extensive review of our tests and we can leave the revision until then to work on development. Once we merge #143, we can probably just close this.

**Comment by cavestruz** [comment]
@matthewkirby @aimalz - just wanted to comment that @mijinyoon is completing/cleaning up tests in test_polaraveraging.py.  Though PR#143 was merged, I think there were remaining items to do.
