### ISSUE TITLE
Take into account error bars in the end-to-end demo pipeline minimization

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#166]
In the end-to-end pipeline demo of branch issue/77/lego-pipeline, `demo-pipeline.ipynb`, error bars on the shear profile are not taken into account at the minimization stage. This need updating.

**Comment by shenmingfu** [comment]
Hi Celine, do you mean the `nfw_to_shear_profile` in Section `Construct model`? We can change the return `sum((gt_model - gt_profile1) **2)` into `sum((gt_model - gt_profile1) **2/gt_err**2)`, and before that we define `gt_err = res['gt_err']`. 
I found `gt_err` (from `polaraveraging.py`) is calculated by `compute_radial_averages` in `utils.py` (using `std` in `scipy.stats.binned_statistic`). We also need to consider the degree of freedom (`n` or `n-1`) when calculating the standard deviation.

**Comment by combet** [comment]
Yes, that's what I meant (having `sum((gt_model - gt_profile1) **2/gt_err**2)`). Simply having this to close that issue is sufficient.

However you're raising a good point regarding the dof. Looking at `scipy.stats.binned_statistic`, it appears in uses `n` to calculate the `std`. And I don't see a keyword to change that.`n-1` is less biased I think as we don't have an a priori knowledge of the mean value in the bin. `numpy.std` would allow it with its `ddof` keyword. This would be a separate issue though if we want to go down that route.

**Comment by shenmingfu** [comment]
I double checked `statistic='std'` in `binned_statistic` is the same as `numpy.std` and the default is `ddof=0`. We can build functions in `compute_radial_averages` (in `utils.py`) to solve this.
