### ISSUE TITLE
Cleaning notebooks in `CLMM/examples`

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#170]
- Remove some old notebooks in `CLMM/examples`.
- Check that `demo_of_polaraveraging.ipynb` is working fine.

**Comment by matthewkirby** [comment]
I just went through to ensure everything runs after my linting and wanted to comment here on my findings. There are a lot of notebooks in master.

- `run_function_on_GalaxyCluster.ipynb`: 
    - This isn't something we do anymore
    - This isn't runnable as it needs `core` and `GCData`. `core` is part of the old code base as is `GCData` (rumor has it this is staying? but idk I think it should be removed at this point.)
    - Matt Kirby Opinion: Remove it
- `rewrite_shearAzimuthalAverager.ipynb` 
    - This looks like it was made to develop code that was moved to a module.
    - The functions made here are all in master in python files.
    - Matt Kirby Opinion: This was a development file that shouldn't have made it to master, Remove it.
- `modeling_demo.ipynb`
    - Demos the functionality of `modeling.py`.
    - Looks great but not runnable!
    - API was updated to correct a redshift bug. This file was not updated to compensate.
    - Matt Kirby Opinion: Update this file to the current API and be sure that we test these things before merging a PR that edits any code in the `clmm/` directory.
- `import_mock_data_as_GalaxyCluster_object.ipynb`
    - What a name. Might want to think about renaming this maybe `generate_mock_GalaxyCluster.ipynb`?
    - Looks great and runs
    - Matt Kirby Opinion: Move code to `generate_mock_data.ipynb` and remove this notebook
- `generate_mock_data.ipynb`
    - Demos making mock data and playing with it
    - There is some code commented at the bottom using shearAzimuthalAverager. Let's remove that.
    - Why don't we show making a GalaxyCluster with this data here?
    - Matt Kirby Opinion: Add contents of `import_mock_data_as_GalaxyCluster_object.ipynb` here and remove `import_mock_data_as_GalaxyCluster_object.ipynb`
- `demo_pipeline.ipynb`
    - Looks great and runs.
    - Some of the plots have two units on the axis labels with a question mark. Lets figure out what units our functions are returning and correct that
    - Matt Kirby Opinion: Establish what units our functions are returning and why are they not Mpc h^-1? Add this to the function docstrings. Correct the axis labels in this notebook
- `demo_of_polaraveraging.py`
    - Works and looks great!
    - Matt Kirby Opinion: Fantastic!

**Comment by cavestruz** [comment]
Okay, just went through the ipynb requests by @matthewkirby .  Issuing a PR now.
