### ISSUE TITLE
Test relevance

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#176]
- [ ] Especially the cross-shear values - are these physical cases we want?
- [ ] Where are the numbers/expected things from?
- [x] Compare shear values with other libraries, e.g. numcosmo's output.  Put note that "These numbers come from numcosmo calculation with X function
- [x] #158

**Comment by cavestruz** [comment]
Hi @mijinyoon and @combet ,  if y'all are signing in to start your friday hack shortly,

@aimalz and I think that there's a need for 
- [ ] Tests that catch the cross-shear bug that was found covering the interaction between multiple functions in polaraveraging.py
- [ ] modeling.py would also benefit from tests of mutual consistency
- [ ] Documentation, i.e. the ipynb examples for modeling, can use more pedagogical descriptions of weak lensing background material.  The ipynb files will be automatically converted to render in readthedocs

**Comment by combet** [comment]
I'm starting to look at this issue, starting with the 3rd bullet point on documentation of the modeling notebooks

**Comment by combet** [comment]
`modeling_demo.ipynb` now updated with more descriptions. Failed to run `pycodestyle_magic` on it due to error when trying to load it.
