### ISSUE TITLE
Tests in modeling.py

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#183]
- [ ] Nothing is inside functions.
- [ ] We should have at least one test function per function in `modeling.py`. Each function can contain as many asserts as you want.
- [ ] Ensure everything is tested

While doing other development, I discovered the following:
- [ ] `get_critical_surface_density` currently not being tested. I changed the values of the speed of light and newton's constant in this function, recompiled, and ran the tests. Everything passed even though the output should be wildly different.

**Comment by matthewkirby** [comment]
Related to:
- Issue #175: test coverage
- Issue #162: Validation tests

**Comment by m-aguena** [comment]
Covered by issue #200
