### ISSUE TITLE
User Feedback on Documentation

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#189]
- [x] Add plots to example code in readthedocs (needs to come from ipynb with outputs)
- [x] Consistency in Notebook naming conventions
- [x] "Auto-compile" the ipynb so we have the .rst files for readthedocs.io
- [x] After ^, remove the lines in CONTRIBUTING.md that talk through individually converting ipynb to rst

**Comment by cavestruz** [comment]
Feedback from Peter Brown @pbrown801
- [ ] git clone -- need https://github.com/LSST/DESC/CLMM.git
- [ ] need to do python setup.py install --user
- [x] fails with syntax error - possibly a python version, saw difference between `which python` and `python -V` Definitely need python 3.  Need to make clearer in doc that python 3 is needed. 
- [ ] Consider moving requirements above installation.

**Comment by shenmingfu** [comment]
> Feedback from Peter Brown @pbrown801
> 
> * [ ]  git clone -- need https://github.com/LSSTDESC/CLMM.git
> * [ ]  need to do python setup.py install --user
> * [x]  fails with syntax error - possibly a python version, saw difference between `which python` and `python -V` Definitely need python 3.  Need to make clearer in doc that python 3 is needed.
> * [ ]  Consider moving requirements above installation.

I will open another issue for these. Regarding "Consider moving requirements above installation", I guess I will also copy those newly added instructions in #191.

**Comment by aimalz** [comment]
- [ ] When running `pytest` after installing `clmm`, we don't check that the user is doing so with Python 3.7.  Is there a way to do this?

**Comment by shenmingfu** [comment]
The "example" link on `README.md` is currently linked to an old branch. But issue/196 is closed. I will change it to master branch and make a commit in issue/189. @matthewkirby

**Comment by shenmingfu** [comment]
There are still some minor problems in README.md (difference between '_' and '-'; missing '_' or '-').  They don't strongly affect reader/user to understand the readme. We can fix them in a future issue.

**Comment by matthewkirby** [comment]
Yeah. Lets not worry about minor things like that. Before v1.0 we should go through and scour spelling, grammar, small typos and fix em all. Might as well wait until we are at that stage though rather than doing it multiple times.

**Comment by matthewkirby** [comment]
> When running pytest after installing clmm, we don't check that the user is doing so with Python 3.7. Is there a way to do this?

We can check this in the `setup.py` I will do this real quick and open up a PR. I want to test our minimum python version that works but I am doing that with travis right now. Should be super super fast.

**Comment by cavestruz** [comment]
I believe we'd covered the pieces of feedback on documentation here and those changes are merged to master, so closing this issue.  We can reopen another issue for more User Feedback.
