### ISSUE TITLE
Adhering to the Style Guide

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#19]
The style guide for python is: https://www.python.org/dev/peps/pep-0008/

Summary below

**Comment by matthewkirby** [comment]
__Naming Things__

- `_single_leading_underscore` : Weak "internal use" indicator. `from module import *` will not import these for instance
- `__double_leading_underscore` : when naming a class attribute, invokes name mangling (inside class FooBar, __boo becomes _FooBar__boo).
- `single_trailing_underscore_` : Used to differentiate between a python keyword and variable (class and class_ for instance)
- `__double_leading_and_trailing_underscore__`: "magic" objects or attributes that live in user-controlled namespaces. E.g. `__init__`, `__import__` or `__file__`. Never invent such names; only use them as documented.

- Python packages: Short in all lower case with no underscores
- Classes: CamelCase with no underscores
- Function and variables: All lowercase with underscores between words
- Global constants: All capital letters with underscores

**Comment by cristobal-sifon** [comment]
also, please do your best to adhere to the line length suggestions (https://www.python.org/dev/peps/pep-0008/#maximum-line-length):

 * Limit all lines to a maximum of 79 characters.
 * For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

**Comment by matthewkirby** [comment]
Regarding this, as soon as we have code in `master`, I am going to issue a PR for the travis branch which will run pylint and enforce style.

**Comment by matthewkirby** [comment]
Now that we are not spending all day every day working on this repo. Do you think that it is a good idea to start enforcing this? I can fix everything that is in master so far and add pylint to travis if so.

**Comment by aimalz** [comment]
@matthewkirby I think that would be very reasonable.

**Comment by cristobal-sifon** [comment]
@matthewkirby yes!

**Comment by matthewkirby** [comment]
With our major refactor, we should add this to the README and then close this issue.

**Comment by matthewkirby** [comment]
With new code being merged into master, we are a little hasty with style to get our workshop example done.  To close this
- [ ] Detail style instructions this in the CONTRIBUTING
- [ ] Clean up files in master in style and not currently implemented/needed/tested parameters.

**Comment by combet** [comment]
Regarding this issue, I started using pylint but it says I don't have a config file, so it's running a default configuration. @matthewkirby, do you use a specific config file to run pylint and if so, could you put it on the repo so we all use the same?

**Comment by matthewkirby** [comment]
@combet There is actually a very simplistic `.pylintrc` file in the main directory. I usually just run it with default settings and then ignore some things 
- bad continuation when dealing with a long string
- functions that take too many parameters if I cannot simplify it easily
- too many variables in a function if i cannot simplify it easily
- variable names that do not correspond to conventions for things like: ra, dec, z (in very simple functions only)

**Comment by cavestruz** [comment]
It looks like all points have been done, and there is a line on how to run pylint in CONTRIBUTING.md.  Closing this issue.
