### ISSUE TITLE
Some ideas about demo_pipeline.ipynb

### ISSUE THREAD

**Issue by shenmingfu** [LSSTDESC/CLMM#205]
In `examples/demo_pipeline.ipynb` (`Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb`), there are several things that we might need to double check:

- [x] The x-axis unit in "Computing shear" is radian rather than degree.

- [x]  `e1` and `e2` in cluster catalog are considered as (reduced) shear rather than ellipticity. (We might need to adjust the definition of `e1` and `e2` in `mock_data`) 

- [x] In `cluster_toolkit`, the unit of mass is `$M_{sun} h^-1$`, but in CLMM we are using `M_{sun}`.

- [x] `polaraveraging.make_shear_profile` uses `compute_radial_averages` in `utils`, where the error bar is calculated by `std/n`. We might need to consider `std/numpy.sqrt(n)`.

- [x] We might need to make a note in the notebook: if the number of bins is too large, or the bin range is biased, it is possible that some bins have no data, and this could lead to `nan` (or some value divided by zero) in some statistical quantities.

**Comment by combet** [comment]
Simply commenting on the items above: 
- Yes, the label in the shear profile should be radians and not degrees.
- `e1` and `e2` are indeed directly computed from the reduced shear in `mock_data.py`.  @shenmingfu, you're suggesting it's missing a factor 2 to convert to ellipticities? It does depend on the definition we take for ellipticities though, right? 
- Regarding the mass definition, I'm not sure I understand your point. CLMM's modeling uses `Msun/h` so the results of the fit will be in that unit, but that's all there is to keep in mind, no? I might be missing something...
- I agree the error bar on the bin average should be `std/sqrt(n)` and not `std/n` as it is now.
- The issue of empty bins in being addressed in issue #214.

**Comment by shenmingfu** [comment]
Hi @combet , thank you. 

- Yes that's for the factor 2, and yes that depends on the definition of ellipticities. I find this [line](https://github.com/LSSTDESC/CLMM/blob/e7e0859658e813f01a639607cbcc4a5a37cc72a6/clmm/polaraveraging.py#L112) in `polaraveraging` so it is consistent.

- In the notebook [Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb](https://render.githubusercontent.com/view/ipynb?commit=e7e0859658e813f01a639607cbcc4a5a37cc72a6&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4c535354444553432f434c4d4d2f653765303835393635386538313366303161363339363037636263633461356133376363373261362f6578616d706c65732f4578616d706c65315f4669745f48616c6f5f4d6173735f746f5f53686561725f436174616c6f672e6970796e62&nwo=LSSTDESC%2FCLMM&path=examples%2FExample1_Fit_Halo_Mass_to_Shear_Catalog.ipynb&repository_id=122678791&repository_type=Repository#Fitting-a-halo-mass) `Fitting a halo mass` section, the legend on the figure uses unit `Msun`, and that might need to be adjusted.

**Comment by cavestruz** [comment]
- [ ] Consistency in Msun --> Msun/h
- [ ] Make a note in the demo emphasizing the units chosen for mass and why
Note:  Now, in cluster toolkit, M/h.
