### ISSUE TITLE
Demo pipeline using non-ideal mock data

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#206]
From PR #203, the `make_shear_profile` function from `polaraveraging.py` will also return the average redshift in the bin. Then all should be in place for a full demo pipeline where not all sources are at the same redshift (which is currently the case in `demo_pipeline.ipynb`).

I'd suggest including shape noise, the `chang13` redshift distribution and redshift errors to generate the mock data in that example.

**Comment by m-aguena** [comment]
https://github.com/LSSTDESC/CLMM/pull/203#issuecomment-559793507
