### ISSUE TITLE
Concentration and surface density of NFW profile

### ISSUE THREAD

**Issue by shenmingfu** [LSSTDESC/CLMM#207]
Currently we are using `cluster_toolkit` to calculate NFW surface density. The definition of `r200` (Rdelta) in `cluster_toolkit` includes a factor of `(1./Omega_m)**(1./3.)`. We need to multiply our input radii by this factor. We can't just multiply our input concentration by this factor because that would change `delta_c`.  
We also need to divide this factor out in NFW surface density output.

The NFW surface density in `cluster_toolkit` also include a factor of `Omega_m` (definition), and we need to divide it out in CLMM.

For differential surface density, if we directly use the surface density from `cluster_toolkit` as input, we need to divide the result by `(Omega_m)*(1./Omega_m)**(1./3.)`. 

- [ ] Multiply input radii by a factor of `(1./Omega_m)**(1./3.)`

- [ ]  Divide out a factor `(Omega_m)*(1./Omega_m)**(1./3.)` from `cluster_toolkit` NFW surface density output

- [ ] Divide out a factor `(Omega_m)*(1./Omega_m)**(1./3.)` from `cluster_toolkit` differential surface density output if directly use the surface density from `cluster_toolkit` as input 

Another thing we need to pay attention to is that in `cluster_toolkit` the unit of mass is `$M_{sun} h^-1$`.

**Comment by m-aguena** [comment]
@shenmingfu that is not necessarily a bug. It's just that `cluster_toolkit` works with `r200_background` and not `r200_critical`. So by using it, the mass we get is  `m200_background` (and not `m200_critical`).

We should be explicit about it though in the documentation, or add a parameter to config this.
@matthewkirby do we have this written somewhere?

**Comment by shenmingfu** [comment]
#282
