### ISSUE TITLE
Fix source redshift generation in mock_data.py

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#208]
When generating redshifts from the Chang et al. (2013), some source redshifts are drawn below `z_cluster + 0.1`, while line 187 of `mock_data.py` explicitly aims at having `zsrc_min = cluster_z + 0.1`(at the moment, the 0.1 is hard-coded). So this is a bug. This issue should serve to fix two aspects:
- let the users define the `zsrc_min` they want;
- ensure that no sources are drawn below `zsrc_min`.

This was spotted by @m-aguena in PR #203.

**Comment by marina-ricci** [comment]
I think this is due to the way photo-z errors are computed (i.e. they are added after the source selection is performed). We should first 1) simulate the source redshift distribution, 2) add redshift errors if needed, 3) perform a selection cut.
