### ISSUE TITLE
Flag empty bins after polaraveraging

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#214]
At the moment we are not checking if all the bins have galaxies in them and empty bins will cause the fit to crash. There are different ways to deal with it, but I'd suggest simply adding the number of galaxies in each bin in the profile table of the GC object. We can then decide the ignore the 'bad' bins for the fit at a later stage.

**Comment by cristobal-sifon** [comment]
if we're doing this at the user level, then it is simplest to change the fitting code as in ``Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb`` to simply identify ``nan`` values in either `r`, `gt_profile`, or `z_src_rbin`:

```python
def nfw_to_shear_profile(logm, profile_info):
    [r, gt_profile, z_src_rbin] = profile_info
    mask = np.isfinite(gt_profile)
    m = 10.**logm
    gt_model = clmm.predict_reduced_tangential_shear(r[mask]*cosmo.h,
                                                     m, concentration,
                                                     cluster_z, z_src_rbin[mask], cosmo,
                                                     delta_mdef=200,
                                                     halo_profile_model='nfw')
    mask = np.isfinite(gt_profile)
    return sum((gt_model - gt_profile[mask])**2)
```

I believe this is equivalent to what was sought by storing the number of objects in each bin. If this would satisfy people (for now) I can go ahead and submit a PR by tomorrow.

**Comment by combet** [comment]
Thanks @cristobal-sifon. I agree that for this particular example, it would be sufficient to do what you propose. For the slightly more complex case where errors on `gt` are taken into account, as in `Example2_Fit...`, the mask needs to check for `nan` for both `gt` and `gt_err` (to be on the safe side).

Nonetheless, I think that having the number of galaxies in each bin would be interesting information to have in the profile table for the user, so I'd be tempted to add this field in the profile table anyway.

**Comment by cristobal-sifon** [comment]
fair enough. Will look into it.
