### ISSUE TITLE
Make polaraveraging compatible with different data input

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#216]
We would like to make polaraveraging more modular by being able to work with either ellipticities or shear or reduced shear. 
- We need to remove the warning and error messages based on the columns names.
- We need to add a  keyword for the user to specify the data type given in input e.g. 'ellipticities', 'shear' and 'convergence' or 'reduced  shear'.
- We need to operate the transformation to reduced shear if needed.

**Comment by cavestruz** [comment]
Converting @marina-ricci 's comment to checkmarks

- [ ] We need to remove the warning and error messages based on the columns names.
- [ ] We need to add a keyword for the user to specify the data type given in input e.g. 'ellipticities', 'shear' and 'convergence' or 'reduced shear'.
- [ ] We need to operate the transformation to reduced shear if needed.

**Comment by rherbonnet** [comment]
Thoughts for conversion function so that whatever the user inputs there will always be the same definition of the columns 'e1' and 'e2' in the astropy table (galcat) for the GalaxyCluster object

def helper_function(chi_1=None,chi_2=None,epsilon_1=None,epsilon_2=None, axis_ratio=None, position_angle=None, reduced_shear_1=None,reduced_shear_2=None,shear_1=None,shear_2=None, convergence=None):
          '''User can input whatever their catalogue gives and this will always return reduced shears 1 & 2, which can be put into an astropy Table for GalaxyCluster object'''
          return reduced_shears_1_and_2

**Comment by combet** [comment]
Thanks for the helper function @rherbonnet. Could you please double check the implementation of the conversion between chi et epsilon?

I think there's a set of parentheses missing at the denominator of the conversion factor, i.e. `chi_conversion = 1./(1.+(1-(shape_1**2 + shape_2**2))**0.5)` from Bartelmann & Schneider (https://arxiv.org/pdf/astro-ph/9912508.pdf).
![Screenshot 2020-03-25 at 15 08 34](https://user-images.githubusercontent.com/20227809/77545302-85697c80-6eaa-11ea-9387-1fc6e60ffe89.png)

**Comment by rherbonnet** [comment]
Yes that would be more readable, but since it's all additive between the parentheses, I don't think it matters. Right? I will change it to your suggestion, though

**Comment by combet** [comment]
But there's the minus sign in front of the parenthesis I added, so no, it's not the same. Or am I missing something really obvious?

**Comment by rherbonnet** [comment]
aaaah you're right, no I was missing something obvious :)
Anyway I did add the parentheses, so it should be fine now. Good you checked!

**Comment by rherbonnet** [comment]
should we put in a check for too large ellipticities? I'm doing some quick tests of the function now and |chi|>1 returns imaginary epsilon values, as you would expect. But I think there could be |chi|>1 cases for very noisy galaxies. 
Should we just return the imaginary result? I don't think we should cap them at 1, that would bias the measurement, but the imaginary results might break stuff later on in the script

**Comment by rherbonnet** [comment]
I also wrote a quick simple test function to go from moments to ellipticities and check the chi->epsilon conversion. It works :) Do we want that test anywhere?

**Comment by combet** [comment]
We definitely need to test that function as part of our test suite. Could you please add it to `CLMM/tests/test_utils.py`? Would be good to also test there the other conversion options.

**Comment by combet** [comment]
I think I might have encountered some |chi|>1 values working with the DC object catalog as I got some NaN for some galaxies when computing the tangential shear. Didn't pay too much attention to it, but I realise now this might have been the problem. In the "DC2 object lensing cuts tutorial, they filter on 'shape_hsm_regauss_etot < 2', suggesting that we could indeed keep galaxies with |chi|>1, but I'm not sure how to best deal with those down the line.

**Comment by rherbonnet** [comment]
I've added a tester function to test_utils. 
Is nan's in the shape catalogue something we should worry about here or can we close this issue?

**Comment by combet** [comment]
Thanks for the test! For that issue, I don't think we need to worry about the NaN in that particular issue. We can deal with them later on.

So could you open a pull request to merge that branch into `master`? We'll close the issue only when the PR is accepted and the merging done.

**Comment by combet** [comment]
Merged in PR #258. Closing issue.
