### ISSUE TITLE
Add a sampler module

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#220]
Create a sampler module based on a likelihood input. We can just stat with something simple like a minimizer.

**Comment by cavestruz** [comment]
- [ ] Decision from 1/31 call is to (for now) have a .py file in examples so the demo notebooks are cleaned up.  Create .py file with the minimizer.
- [ ] Use the .py file as module in demos.

**Comment by cavestruz** [comment]
Closed with PR #227
