### ISSUE TITLE
Updating notebooks unclear in CONTRIBUTING.md

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#234]
- [x] Check that the instructions work
- [x] Update CONTRIBUTING.md to be clearer (e.g. with a new header after merging PR)
- [x] Table of contents to CONTRIBUTING.md

**Comment by cavestruz** [comment]
- [ ] Need to update CONTRIBUTING.md to specify that notebooks **only** needs to be run in publish-docs branch.

**Comment by m-aguena** [comment]
> * [x]  Need to update CONTRIBUTING.md to specify that notebooks **only** needs to be run in publish-docs branch.

This was actually already adressed in the **Updating Public Documentation on lsstdesc.org** section, but I modified it for clarity.
