### ISSUE TITLE
Implement accounting for measurement errors

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#237]
- [ ] e1 e2 only have stddev, don't take in errors for each.
**Note, not necessary perhaps.**
Also related to Issue ...?

**Comment by shenmingfu** [comment]
The question was asked in #205

**Comment by aimalz** [comment]
Is this redundant with #233?

**Comment by combet** [comment]
No, this is a separate matter I think. Here, we're talking about taking into account shape measurement errors on `e1` and `e2` (`e1_err`, `e2_err`?) that may be provided in the catalogues for each galaxy... at some point in the future. However, it's not clear whether DM stack will/can provide those errors. #233 is simply allowing for shape noise to also act on `g_x` to make the mock data more realistic.

**Comment by m-aguena** [comment]
Part of this issue (passing input error on profile compuation) will be solved in #395, but we still need to include a conversion of (`e1_err`, `e2_err`) - >  (`et_err`, `ex_err`).

**Comment by cristobal-sifon** [comment]
note that there is only one ellipticity measurement error, which is the same in both components per galaxy, whether these two components be `(e_1,e_2)` or `(e_t,e_x)`, so there is no such transformation to make

**Comment by marina-ricci** [comment]
@cristobal-sifon @combet @m-aguena is this issue still to do?
