### ISSUE TITLE
Clearer naming scheme for tables of polaraveraging + new user options

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#248]
At the moment, the columns names of the cluster galaxy catalog refer to `e1` and `e2`. This should be renamed to something more explicit like `reduced_shear_2` and `reduced_shear_2`.

This links to #216 where a helper function will be written to convert any user shape measurement (ellipticiy, shear, axis_ratio, etc.) into `reduced_shear_(1,2).`

**Comment by combet** [comment]
Actually, building on that first comment, there are several aspects we could consider:
- Find a better name for the `e1` and `e2` columns (which is the above);
- Include `component1` and `component2` keywords in `polaraveraging`, that would default to `e1,2` (or whatever) if the user does not specifies them, but that would allow to perform the operation on user-specified columns otherwise. For example, I have columns named `shear1` and `shear2` from simulations and I want the shear profile (not reduced), I could just give `component{1,2}=shear{1,2}` as argument to `compute_shear`. 
- Following from that, we'd then need to give the option to the user to choose the name of the output columns. At the moment it's `gt` and `gx`, but in my example above, I might want to call them `gammat` and `gammax` instead.

What do you think @rherbonnet, @pennalima ?

**Comment by rherbonnet** [comment]
I like the idea, but wouldn't that make it difficult to check against a "shear" or "ellipticity" column being present in polaraveraging.compute_shear?

**Comment by combet** [comment]
Not sure I understand completely what you mean. At the moment, the only test for that in compute shear is (if working with a GalaxyCluster object `if cluster is not None`) is:
`required_cols = ['ra', 'dec', 'e1', 'e2']`
and it complains if any of those are not present in `cluster.galcat`.  Changing that to 
`required_cols = ['ra', 'dec', component1, componenet2]`, where the latter to are new keywords of `compute_shear()` should do the trick, no?

**Comment by rherbonnet** [comment]
Maybe I didn't understand you correctly then. You want to change `e1` and `e2` to `component1` and `component2` in `cluster.galcat `? 
I thought you meant giving the user a way to store whatever variable they want (shear,epsilon,chi,...) in `galcat`

**Comment by combet** [comment]
Sorry I wasn't clear. I think `galcat` could include whatever the user want and maybe columns named `shear1` and `shear2` or `reduced_shear1` and `reduced_shear2` or `ellipticity1` and `ellipticity2` (ok, I stop here). I think it would be good for the user to be able to call

`compute_shear(..., component1='red_shear1', component2='red_shear2',...)` 

so that the operation (multiplying by `(cos2phi,sin2phi)`) is performed on whatever column the user want, given its name in the astropy table. But in defining the function, we should set

`def compute_shear(..., component1='e1', component2='e2',...)` by default, keeping the behaviour we already have. Does that make more sense?

**Comment by rherbonnet** [comment]
Yes, thanks for explaining. For clarity, I think calling it `shape_component1` and `shape_component2` might be better than just `component`

**Comment by combet** [comment]
I just started some edits in branch `issue/248/...` along the lines described above.
- Could you please check the new keywords make sense and are self-explanatory enough
- Are the default values for these new keywords OK, or should we make them even more explicit (i.e. `e1` --> `ellipticity1`, etc.).

**Comment by combet** [comment]
So to summarize the changes so far in `polaraveraging.py`:
- [x] Renamed `compute_shear` to `compute_tangential_cross_components`
- [x] Renamed `make_shear_profile` to `make_binned_profile`
- [x] Added optional column name keywords to both functions (see the code)
- [x] Propagated the changes throughout the code base

To be done:
- [ ] Get feedback and agree on the proposed name change. @aimalz, @marina-ricci, @rherbonnet 
- [ ] Update the documentation to better reflect the now more generic behavior of these functions. @aimalz you volunteered if I remember correctly. ;)
- [ ] Update the `demo_polaraveraging` notebook to add a section exemplifying the new flexibility (i.e. users are free to use columns named what they want - and containing ellipticity, or shear, or reduced shear...).

**Comment by rherbonnet** [comment]
Here's a bunch of thoughts. Some are small things I can fix myself, but it's late now, so I'm just putting them here, so I won't forget after the weekend.

- Maybe just for the really new user, change `compute_tangential_cross_components` to `compute_tangential_and_cross_components`? 
- The docstring for it also has the typo `cluser`
- Line 130 `shear1, shear2 = cluster.galcat['e1'], cluster.galcat['e2'] ` in `compute_tangential_cross_components` should be `shear1, shear2 = cluster.galcat[shape_component1], cluster.galcat[shape_component2] `, I think
- There are still the arguments `shear1` and `shear2`, but it seems silly to me to change them to `shape1/2` or `shape_or_shear_or_reducedshear`. I think just an addition to the doc string stating that instead of shear another variable is also fine.
- Change the functionality of `plotting.plot_profiles` to accept user defined shape_components as well?

**Comment by combet** [comment]
Thanks for looking into it @rherbonnet, and for catching the remaining `galcat['e1,e2']`, which would have defeated to whole point of the exercise! 

I agree with all your other points, including not changing the argument named `shear1,2` but simply adding something in the documention mentioning it could be something else than shear.

**Comment by rherbonnet** [comment]
I've changed the code according to the first 4 bullet points above, but I'm thinking of using the existing structure of `plotting.plot_profiles` to accept other column names than `et` and `ex`.
I want to change the arguments from
`tangential_shear: array_like, optional`
        `The tangential shear at the radii of rbins`
to 
`tangential_shear: array_like, string, optional`
        `The tangential shear at the radii of rbins or the column name of the cluster Table corresponding to the tangential shear`
Or would people prefer extra arguments to keep the existing structure intact?

**Comment by combet** [comment]
Thanks for those changes @rherbonnet. 

Regarding `plot_profiles`, I agree that it would be nice if the users could specify the column they want to use. It will generally contain (reduced) shear but once we have the `DeltaSigma` from data implemented, the user may want to plot the `DeltaSigma` tangential and cross profiles. In that case, having the argument called `tangential shear` might be confusing? What about calling it `{tangential,cross}_componenent` instead?

**Comment by combet** [comment]
Ah, also, there's now `table_name` keyword in the `make_binned_profile` function that allows the user the actually choose the name of the cluster object's attribute that will contain the binned profile. This flexibility needs also to be included in `plot_profiles` as, at the moment, it looks only in the `profile` table.
