### ISSUE TITLE
Binning scheme allowing for a given number of galaxies per bin

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#253]
So far, the only binning scheme we have readily available for the user is evenly spaced in linear or log space. The resulting inner bins have generally very low number of galaxies. It would be very useful to provide a solution that returns bins with a user-defined number of galaxies in them, given the galaxy catalog.

**Comment by rherbonnet** [comment]
You could simply define a number of bins and use percentiles to get the bin edges.
def get_bins(arr,nbins):
    return np.percentile(arr,tuple(np.linspace(0,100,nbins+1)))
For some reason the function only works if you give it a tuple, not an array
I quickly checked that it gives equal occupations in bins in a rayleigh, gaussian, uniform distributions

**Comment by combet** [comment]
Thanks @rherbonnet, that's a very nice solution. I've checked it out on the galaxy distribution we have in the notebook and it's working nicely. Need to code it up properly somewhere in the code now...

**Comment by combet** [comment]
Hi @rherbonnet, so I added the function `make_bins_with_same_ngal` in `utils.py`, in branch issue/252/binning. Could you please check it out and tell me if you think something is missing?

**Comment by rherbonnet** [comment]
wow, you expanded way more than I had thought.
I was just thinking of adding the oneliner in utils.make_bins with some option 'evenoccupation'
Maybe I'm being slow, but could you tell me why the units are made the same here, does that matter for the binning?

**Comment by combet** [comment]
Thanks Ricardo. You're right I made it far more complicated than necessary (I woke up very early today and decided to do some coding... clearly I was not really awake.) 
But just to clarify:
- I wanted to have the option to ask e.g, for a binning in Mpc given an separation array in radians. This is because compute_shear() will add the separation in radians for each galaxy in gal_cat, but we may want to provide a binning in Mpc to make_shear_profile(), to directly get the profile in that unit. But it would have been much simpler to do the conversion after the bins are done (in whatever unit the separation array was passed).
- I also agree it would much neater to have it as a new option in make_bins!

Feel free to change it as you fit if you have time today. Otherwise, I'll take care of it tomorrow (I'd like to have the PR ready tomorrow by tag up).

**Comment by rherbonnet** [comment]
I'll look at it later today

**Comment by rherbonnet** [comment]
I've pushed the code, please look it over when you have time. It's basically what @combet wrote minus explicit checks for units.

**Comment by combet** [comment]
Thanks @rherbonnet, it's great thanks! I've added an example use in section 3.2.2 of `demo_polaraveraging_functionality`. If that's OK with you, I think we can open a PR.

**Comment by rherbonnet** [comment]
Great idea, yes. I'll make a PR. Thanks

**Comment by combet** [comment]
Done in PR #265. Closing issue.
