### ISSUE TITLE
CLMM and NumCosmo comparison

### ISSUE THREAD

**Issue by vitenti** [LSSTDESC/CLMM#254]
In the comparison between CLMM modeling (using cluster toolkit) and NumCosmo, we found that the notebook modeling_cmp_numcosmo.ipynb gives suboptimal results. This happens for two different reasons:

- The value of the gravitational constant G in CLMM comes from astropy, thus, if you use astropy version < 4.0 it uses G from CODATA 2014 and if the version is >= 4.0 it uses G from CODATA 2018. Moreover, the value of the solar mass comes from the GSL (as it was in CCL, which was already updated). This relates with the issue #156 .

- The cor_factor was set to 1, whereas it should account for these differences in rho_critical. In addition there is cor_factor in wrong places.

We updated the notebook, fixing the above issues.

**Comment by aimalz** [comment]
For completeness @m-aguena, do you think this is a continuation of #162?  In any case @vitenti, it sounds like this issue is ready for a Pull Request.

**Comment by pennalima** [comment]
@marina-ricci, is the magnification going to be included in modeling? 
@aimalz and @m-aguena, I was planning to complete the magnification comparison before doing a pull request.

**Comment by marina-ricci** [comment]
@pennalima Yes it will be included (if other agree on that). I am waiting for PR 264 and PR 266 before updating my PR because we are all working in `modeling.py`. Then I would need some help to implement the tests.

**Comment by pennalima** [comment]
@marina-ricci Let me know when you implement the tests. I could help you.

**Comment by vitenti** [comment]
For those interested, you can run NumCosmo + CLMM + Colossus online using the following link: 
https://mybinder.org/v2/gh/NumCosmo/NumCosmo/master

- The notebook NC_Colossus_density_profiles.ipynb shows the comparison between NumCosmo and Colossus.
- The notebook modeling_cmp_numcosmo.ipynb shows the comparison between NumCosmo and CLMM.

If that is something useful for any of you, I can prepare docker images containing NumCosmo + CLMM and others.
