### ISSUE TITLE
Error in modeling when z_source < z_lens

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#257]
In clmm/modeling.py there is no warning or error when z_source < z_lens and the functions return non zero values. This is incorrect.

**Comment by combet** [comment]
@marina-ricci, I looked into it and tried to fix it. Could you please checkout branch issue/257/... and also tentative PR #266 to see if this does what you were expecting?

**Comment by combet** [comment]
Done in PR #266. Closing issue.
