### ISSUE TITLE
Improve profile table

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#259]
As originally suggested in #122, it would be good to have clearer profile table by attaching cosmology, units and bin definition to them
- [x] Attach cosmology to meta data of profile table
- [x] Add units to meta data of profile table
- [x] Add bin definition to meta data of profile table (already included since bin edges info is there)

**Comment by m-aguena** [comment]
@cavestruz isn't "bin definition to meta data of profile table" already described by the `radius_min`, `radius_max` columns?

**Comment by cavestruz** [comment]
@m-aguena - I'm trying to remember the context of this, but I *think* it had to do with whether or not the profile was constructed with binned individual clusters or not.  @combet - do you remember this point?
