### ISSUE TITLE
Need to request software added to the nersc environment

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#26]
- [x] `pip install py.test`
- [x] `pip install sphinx-apidoc`
- [x] `pip install lmfit`
- [x] `pip install CosmoloPy`

**Comment by cavestruz** [comment]
Need this for documentation and testing!

**Comment by mchoi8739** [comment]
pip install CosmoloPy

**Comment by aimalz** [comment]
I'm closing this issue because all the checkboxes have been checked off.
