### ISSUE TITLE
Adapt integration ranges in modeling.py to the user-defined r_proj argument 

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#262]
Numerical integrations are performed by cluster toolkit to compute Sigma and DeltaSigma. The function being integrated, e.g rho or Sigma, needs to be defined on a domain that encompasses the `r_proj` array for which the user is requesting the evaluation. At the moment, this underlying domain has hard-coded values in `modeling.py`, and if it's not adapted to `r_proj`, this returns no clear error or warning. This should be changed to automatically adapt to whatever radial range is covered in r_proj.
- [ ] in `modeling.py` change any hard-coded instance such has `sigma_r_proj = np.logspace(-3, 4, 1000)` (line 271) to something like `sigma_r_proj = np.logspace(np.log10(r_proj[0])-1 , np.log10(r_proj[-1])+1, 1000)`
- [ ] If `r_proj` requests too small values, say < 1e-5, return a warning?

(Extending the range by one order of magnitude, like in the example above, might be overkilling it?)

**Comment by combet** [comment]
Adding to the above, looking at where cluster-toolkit complained, the smallest radial range for the integrand needs to be at least that of the user-defined range when calling `predict_excess_density`, etc. While working OK with this minimal radial range, the validation tests, comparing to NumCosmo, results were failing for rtol=1.e-8. While passing with rtol=1e-7, I opted for keeping the current 1e-8 requirement and adjusting the integration range for it to pass. That led to:
- [ ] `sigma_r_proj = np.logspace(np.log10(r_proj[0])-1, np.log10(r_proj[-1])+1, len(r_proj)*10)`  in `predict_excess_surface_density`;
- [ ]  raising an error for very small radii (<1.e-11 Mpc/h) in DeltaSigma, where the kernel was consistently crashing.

**Comment by combet** [comment]
This has been merged, so closing for now. Might be reopened if required.

**Comment by combet** [comment]
@rherbonnet just noticed that the modification cannot handle the case when r_proj is a float and not array-like. A small fix needs to be implemented in `modeling.py`. Reopening this issue until fixed.

**Comment by rherbonnet** [comment]
Just pushed the fix. Instead of using if statements, I used np.array(r_proj).size assuming and hoping that the user is not going to give a more than 1D array of projected distances

**Comment by combet** [comment]
Thanks @rherbonnet. This works well. Looking at it I also realized that if `np.array(r_proj).size` is small, then `Sigma` will be evaluated in only a few radii and we'll lose precision in the numerical integration to get `DeltaSigma`. So I've push a small modification imposing at least 1000 points for `sigma_r_proj` (I did some quick convergence tests in the regime we're likely to operate and 1000 points seem OK).

I think this covers it. If you agree, please open a PR :)

**Comment by combet** [comment]
Done in PR #270. Closing issue.
