### ISSUE TITLE
Bug in cluster_toolkit affecting modeling.py

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#267]
I believe there are some bugs with the python wrapper of `cluster_toolkit`which propagate to CLMM/modeling.py. This includes silent crash, never ending computation or wrong results. So far, I noticed issue with the data type of the radius `r3d`. 

- when `r3d` is given as an 'int' instead of a float, no issue is raised but `get_3d_density` gives wrong result and `predict_excess_surface_density` crashes silently. This could be adressed by imposing `r3d` to be a float.

-  depending how `r3d` is computed,  `get_3d_density` may give wrong result and `predict_excess_surface_density` may crash silently. However, in python, I can not understand why it works or not as the data type of `r3d` is 'float64' in any case

This behaviour is illustrated in https://github.com/LSSTDESC/CLMM/blob/issue_267_bug_in_ct_and_modeling/examples/Bug_tester.ipynb

**Comment by vitenti** [comment]
I just pushed a commit on this issue branch and I think it fixes the problem. Please check if it does not break something else.

**Comment by combet** [comment]
@marina-ricci, @vitenti I don't think there has been a PR for this yet. If you think it's ready, please open one up so it may be reviewed and merged!

**Comment by vitenti** [comment]
I just applied the fix directly in issue/282/modeling_structure (#282), I also copied the notebook that evinced the bugs. You can take a look there and close this and delete the branch.

**Comment by combet** [comment]
OK - thanks
