### ISSUE TITLE
list of minor things that need to be modified

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#268]
This is a list of minor things that need to be modified. Once the list is long enough we can consider making a PR. Some of these might already been fixed by previous PR.

- [x] The documentation of function `compute_radial_averages` in `utils.py` was not updated after PR# 255

- [x] The redshift cut in `mock_data` should be done differently to avoid error messages because of z_source<z_cluster. 
- [x] The boxsize in `mock_data` is set to be 4 Mpc/h * 4 Mpc/h, instead what is given in the doc. This is starnegely defined and should be more flexible (e.g. giving source density instead of number of galaxies) 
- [x] `compute_shear()` returns a catalog with bad column names (ra, e1, e1 instead of theta, gt, gx)
- [x] `compute_shear((cluster_ra, cluster_dec, gal_cat['ra'], gal_cat['dec'], gal_cat['e1'], gal_cat['e2']))` does not work
- [x] `cl.plot_profiles` => the documentation should mention that is returns both 'fig' and 'ax'
- [x]  `sampler.py` is quite cryptic. I do not see the need to make an if statement in `def scicurve_fit`
- [x]   `cl.plot_profiles` is not plotting the cross-shear component.

**Comment by combet** [comment]
Updates in the code since this issue was open:
- `cl.plot_profiles` not plotting the cross-shear component has been fixed as a side product in #248 
- `compute_shear` has been renamed `compute_tangential_and_cross_components` and modified for more flexibility in #248.
- Anything about `mock_data` should be addressed in #284

**Comment by marina-ricci** [comment]
- [ ] The documentation of function `compute_radial_averages` in `utils.py` was not updated after PR# 255
- [ ] `cl.plot_profiles` => the documentation should mention that is returns both 'fig' and 'ax'
- [ ]  `cl.plot_profiles` =>not working when there is no "g_t" column (e.g. becaus euser changed the name to `g_tan`)
- [ ] In the `demo_polaraveraging_functionality` notebook documentation : in Section " 4.2. User-defined naming scheme " change "shear_profile" to "reduced_shear_profile"
