### ISSUE TITLE
compute_shear in polaraveraging actually produces reduced shear

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#275]
The function  `polaraveraging.compute_shear` actually produces reduced shear. Should we rename it? Either way, we should definitely update its documentation.

**Comment by combet** [comment]
Right, so 
- first, I want to point out that as part of the ongoing discussion in issue #248, I think the user should specify the name of the columns used by `compute_shear` as an option. The operation (multiply the `1,2` compenents by (`cos2phi,sin2phi)`) can be done on ellipticities, reduced shear, or shear and imposing it to work on the columns named `'e1'` and `'e2'` is very restrictive. 
- If we go for that, `compute_shear` becomes an even worse name. What this function does is return the cross and tangential components of the input columns (`'e1'` and `'e2'` for the moment, but could be others if we implement the first point). So what about `compute_tangential_and_cross()`?

**Comment by combet** [comment]
Along the same line, I also realized that `make_shear_profile()` is poorly named as well as it is very restrictive. It would be better to have it called `make_binned_profile()` as it could simply take the average in bins of whatever tangential and cross component the user provides in the `galcat` table. Default would be to produce the reduced shear, but could also do that for shear, or DeltaSigma if those are available in the table.

**Comment by aimalz** [comment]
Is this also taken care of by #283?
