### ISSUE TITLE
Modeling: cross-check CCL, NumCosmo, Colossus...

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CLMM#277]
The (probably) new structure concerning modeling.py must guarantee that all possible codes are cross-checked.

**Comment by aimalz** [comment]
I think this issue supercedes #254, so I'm going to close that one.

**Comment by aimalz** [comment]
To put this into context of other issues/ongoing branches, would it be a fair summary to say that it really pertains to the tests of whatever code we write to address #282, #285, #292, and #293?  If so, this issue need not correspond to a branch/PR of its own; we can instead plan to mark it with the "Don'tWorryWeGotThis" label when the branches for those issues (whose comments now show that they were linked here) are mature enough to have those tests written.
