### ISSUE TITLE
Need a license file in the repo

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#28]
The license file is super important in the repo. The way I have had it explained to me is that without it, we can "technically" get other people in legal trouble for using our code. We can avoid this just by adding one of the licenses to the repo. Is there one that desc requires/recommends?

**Comment by cavestruz** [comment]
Check on restrictions on license based off of clmassmod (legally, what can people do with the code?)  Check if DESC has requirements.

**Comment by drphilmarshall** [comment]
The pub board has provided some guidelines at
https://confluence.slac.stanford.edu/display/LSSTDESC/Publication+Board

>
