### ISSUE TITLE
Modeling structure

### ISSUE THREAD

**Issue by vitenti** [LSSTDESC/CLMM#282]
## CLMM Modeling structure

Currently, we have a functional structure where all functions receive the full description of what they need to compute. This is partially done through the cosmo object (that can be either an astropy LCDM model or a dictionary) that contains all information about the background cosmology. The parameters related to the halo density profile are all passed one by one in each function. Below, we have the current structure: the  miscellaneous functions do not depend on cosmo nor halo density parameters,  and the other functions depend on the halo density parameters, background cosmology "cosmo" or both.

#### Miscellaneous utilities:

- def cclify_astropy_cosmo(cosmoin):

- def astropyify_ccl_cosmo(cosmoin):

- def _get_a_from_z(redshift):

- def _get_z_from_a(scale_factor):

- def get_reduced_shear_from_convergence(shear, convergence):

#### Halo density profile:

- def get_3d_density(r3d, mdelta, cdelta, z_cl, cosmo, delta_mdef=200, halo_profile_model='nfw'):

- def predict_surface_density(r_proj, mdelta, cdelta, z_cl, cosmo, delta_mdef=200, ...

- def predict_excess_surface_density(r_proj, mdelta, cdelta, z_cl, cosmo, delta_mdef=200, ...

#### Background cosmology:

- def angular_diameter_dist_a1a2(cosmo, a1, a2=1.):

- def get_critical_surface_density(cosmo, z_cluster, z_source):

#### Background cosmology and Halo density profile:

- def predict_tangential_shear(r_proj, mdelta, cdelta, z_cluster, z_source, cosmo, delta_mdef=200, ...

- def predict_convergence(r_proj, mdelta, cdelta, z_cluster, z_source, cosmo, delta_mdef=200, ...

- def predict_reduced_tangential_shear(r_proj, mdelta, cdelta, z_cluster, z_source, cosmo, ...

- def predict_magnification(r_proj, mdelta, cdelta, z_cluster, z_source, cosmo, delta_mdef=200, ...

The proposal is to **keep this current structure** (at least as backwards compatibility) and then build an object structure around them. This seems natural since the targeted back-ends (CCL, NumCosmo) already use an object structure. This framework has several advantages, for instance, if the parameters necessary to describe a halo density profile changes, we do not need to modify the API (the arguments of the functions) since they will be contained inside a single object. Furthermore, if the profile needs some internal computation to be able to compute the observables (say, a spline with the 2D projection), then, a functional structure necessarily has to recompute on every call of a function (one cannot guarantee that all parameters will be the same between calls, it is possible to try to improvise some solution, but it will most probably be error prone). On the other hand, on an object structure, once the object has all its parameters set, then the internal computation is done and the methods computing the observables can be called as many times as necessary. 

In practice we just need to create a class for the Halo profile with the necessary methods to be implemented. Then, for each back-end will be a simple encapsulation of the current CCL and NumCosmo objects. 

If you all agree, I can start with both interfaces: a functional one mirroring the current and an object oriented one.

**Comment by cavestruz** [comment]
Quick note to link #207 when this becomes a PR.

**Comment by vitenti** [comment]
To try the NumCosmo interface please use the latest master version!

**Comment by vitenti** [comment]
Changes
-------

All backend related code is in the modbackend directory. The main controlling
file is modeling.py, it decides which backend to load depending on the models
availability and the evironment variable CLMM_MODELING_BACKEND value:

- 'ct', or if it is unset, chooses cluster_toolkit + astropy;
- 'nc' chooses NumCosmo backend;
- 'ccl' chooses CCL backend (incomplete);

Both NumCosmo and CCL implement the abstract class CLMModeling
(clmm_modeling.py). This class holds the documentation for all implementations
(TODO) as well as all other details like units, little-h, etc. We also need to agree
on the names and arguments of the methods.

In addition I added a thin layer on top of the OO implementation called
func_layer.py. It mimics the current implementation based on cluster_toolkit.
Thus, all the other implementations will have the same behavior.

The pytest already works with all backends (CCL is currently removed from the
tests), it uses a module scoped fixture to control which backend to use.
Any code can try a different backend by calling
`os.environ['CLMM_MODELING_BACKEND'] = 'nc'`
**before** importing clmm.

In my opinion the ideal is to migrate to a OO interface (like the one in
NumCosmo and CCL), this can be done by instantiating the NumCosmo or
CCL implementation of CLMModel class instead of using the functional layer.

Other points:
-------------

- Increased a bit the tolerance value required in the distance comparison
  (1.0e-8 =>1.2e-8), CCL does not match with NumCosmo and Astropy at
  1.0e-8 level.
- The cosmology is still defined by a simple dictionary. We have to decide
  how to represent cosmology in a backend independent way.
- CCL and NumCosmo/cluster_toolkit do not agree already in the 3d
  density comparison. It does not differ only by an overall factor, I tried
  fixing that but the difference increases with R.
- Some functionalities are still not present on CCL.
- In CCL the mass-concentration relation is part of the implementation
  of the objects necessary to CLMM. In NumCosmo, Colossus and
  cluster_toolkit, that can be included by setting the concentration
  parameter using the appropriated c(M) relation (usually, these are
  very simple fitting functions). In any case, CCL have a
  `ConcentrationConstant` object that can be used to mimic the other
  codes behavior.
- For the moment being I wrote everything such that it agrees with the
  current results (therefore with cluster_toolkit). I think now it is a good
  moment to decide if the current input, units and little-h choices are
  OK.

Possible bugs
-------------

- In modbackend/cluster_toolkit.py, the implementation of
  angular_diameter_dist_a1a2 uses astropy to computes the distance
  and consequently to_value(units.pc) to compute it in unit of pc.
  However, there is a variable in constants.py (PC_TO_METER) which
  also contain the value of pc in meters. If these two disagree we can
  have inconsistencies. It may be safe, depends on how astropy
  computes the distances.
- In CCL massdef depends on concentration and concentration
  depends on massdef, am I missing something here? To make it work
  I just put by hand one on another after both were created.

**Comment by m-aguena** [comment]
One important thing I don't think we defined properly yet is that the code is set up to compute `m_Delta` (and all other `Delta` properties) as being related to `rho_background` and not to `rho_critical` (this is linked #207). We should make that clear in the documentation.

On a related topic, do we want to have the option of working with `rho_critical`?

**Comment by m-aguena** [comment]
@vitenti just a reminder to merge #288 into this branch before the pull request.

**Comment by cavestruz** [comment]
> One important thing I don't think we defined properly yet is that the code is set up to compute `m_Delta` (and all other `Delta` properties) as being related to `rho_background` and not to `rho_critical` (this is linked #207). We should make that clear in the documentation.
> 
> On a related topic, do we want to have the option of working with `rho_critical`?

@m-aguena I think we do want to be able to work with m_critical, especially for comparison with halo masses in  these spherical overdensities. But, @vitenti: the CCL/NumCosmo backends enable working with critical, no?

**Comment by combet** [comment]
@vitenti, I have a follow-up question related to the above.
- At the moment the functional interface does not have a keyword to choose between "background/mean" or "critical" as the option is not available in cluster-toolkit.
- I understand that with the object-oriented modeling approach you are proposing, this would be an easy switch?
- Should we also implemented the option in the functional interface, returning an error if 'critical' is requested for the cluster-toolkit backend?

**Comment by vitenti** [comment]
- @m-aguena and @combet yes, we should add a keyword to the functional interface, however, we have to be careful with the interaction with mass definition. For instance, virial in NumCosmo computes a Delta that is compatible with rho_crit (that comes from the way the fitting function was obtained), on the other hand, in CCL they adapted the fitting formula for the virial Delta to be compatible with rho_m. That is, for virial there is already an implied background density in NumCosmo virial imply rho_critial and in CCL virial imply rho_m. In practice, we need to assert in our code if both choices are compatible. 
- @combet yes, I think it is easier to deal with these interactions in the OO approach. Indeed, all the checks necessary to assert compatibility between mass definition and Delta virial are already present in NumCosmo and CCL.
- @combet I think it is a good idea to have a generic interface and particular implementations raising errors if the option is not available in them.
- @cavestruz Yes, we have these options already in the new backends, we just need to be careful with possible interactions as I mentioned before. Moreover, in CCL the mass definition object carries a concentration object, there they implement several fitting formulas for ways to compute concentration from the mass. These fitting formulas are usually very simple algebraic functions on the background/profile. We have to decide if we are going to use them or deal with concentration directly (fitting or fixing it).
@m-aguena I just implemented the PR #288 here.

**Comment by vitenti** [comment]
I've just added a very simple notebook that uses the OO interface (see demo_modeling_functionality_oo.ipynb).

**Comment by combet** [comment]
Thanks for the detailed answer @vitenti.
- Regarding the virial definition in CCL vs Numcosmo, I think we could skip that option for the functional interface, where we would just allow a numeric value for Delta and a critical or mean mass definition. In any case, I think virial generally means Delta=178 if memory serves, so it can be recovered easily. That would prevent complications down the line, no?
- For the concentration, until now with CT, it was a value we could either fix or choose to fit with the mass. NC provides the same I understand. I think it is very desirable to have the option to use a mass-concentration relation as well, but for v1.0, I think this is OK if the CCL backend is the only one to provide that option. Others may have other opinions, so we should discuss this further with the group.

**Comment by vitenti** [comment]
@combet 

- I agree, we should avoid the virial option in the functional interface. This kind of branching when one argument of a function may change the meaning of another is very error prone. I think we must find a solution for this only if we plan to keep the functional interface for the long run. Alas, the virial option is a bit more complicated, the two codes actually implement a fitting function that computes Delta as function of Omega_m(z). 
- I also agree that we should keep treating concentration as a simple parameter for the moment. I think that it will be easier to identify the best way to deal with it when we connect the CLMM with a statistics analysis code.
