### ISSUE TITLE
mock_data module: double check everything, improve/update options and improve documentation

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#284]
Need to double check everything in `mock_data` and improve documentation. Especially

- [x] Check/improve documentation, in particular clarify comoving versus proper distance

- [ ] Improve shape noise? Is adding a random gaussian noise to `gt` equivalent to drawing intrinsic `e1` and `e2` and add those to the shear using the `compute_lensed_ellipticities` function we now have available in `utils.py`  ? (Now issue #304 )

- [x] Double check and fix 'ztrue' versus 'zobs' potential bug

- [ ] Write test functions for mock_data (Now issue #303 )

@marina-ricci, please add anything else you notice

- [x] Give the option to pass a density of source galaxies, or a number of galaxies and a box size

- [x] Give the box size as an argument and not a hard coded value.

- [x] Give the type of profile as an argument.

- [ ] Give the source redshift distribution as an argument

**Comment by combet** [comment]
Thanks @marina-ricci for the list of things to add/improve. 

Just a  clarification regarding your last point (source redshift distribution): at the moment, the user uses either e.g. `zsrc=0.8` for a single source plane or `zsrc='chang13'` to get a sources distributed in redshift. What are you suggesting more specifically?

**Comment by marina-ricci** [comment]
Please check that this issue is addressed : 
 - The redshift cut in mock_data should be done differently to avoid error messages because of z_source<z_cluster.

**Comment by combet** [comment]
Did it this morning - should be fine now. Either the user provide a zsrc_min or it defaults to z_cluster + 0.1

**Comment by combet** [comment]
@marina-ricci , @pennalima, I've opened a PR for this issue as all has been adressed but for the tests. This is a bigger task so I've opened a new issue (#303) that focusses solely on writing tests for `mock_data` as this is not as straightforward as the rest.

**Comment by combet** [comment]
>     * [ ]  Give the source redshift distribution as an argument

@marina-ricci, I think you meant passing a user-defined distribution as argument and we concluded at some point that this should be a enhancement for later, right ?
