### ISSUE TITLE
Reorganization/renaming for data-only vs. cosmology-only vs. both

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#285]
This issue aims to more clearly distinguish functions that require an assumption of a cosmology, functions that require a data set, and functions that require both.  A third module will join polaraveraging and modeling to include the clmm-data-type-specific functions that also require a cosmology, i.e. one will not be able to use the same non-utils function call with and without a cosmology.  The same flexibility to call functions directly on unstructured data or on the clmm data types will be retained, and the base code for the generic mathematical functions will only appear once within clmm.

This is related to #282 in that it would enable a more abstracted way to pass information about a data set and/or cosmology to functions within each module as necessary, hopefully reducing the number of keyword arguments and if/else checks that we have to do.  Since the propagation of this reorganization through all the demos and tests may be messy, it's also a good opportunity to rename polaraveraging.

**Comment by combet** [comment]
This is being addressed in various other issues/PR. #311 that implements the CLMM cosmology object; #317 to ensure consistency of the cosmology between GalaxyCluster attributes; #321 that reorganizes `polaraveraging`. There might be more to do at some point, but we agree that for v1.0 this is sufficient. Closing this issue.
