### ISSUE TITLE
make sure code is compatible with both Python 2/3

### ISSUE THREAD

**Issue by cristobal-sifon** [LSSTDESC/CLMM#29]
Here are some general things one can do to make code compatible with both major Python versions in most cases. Of course there can always be more detailed examples when this fails, but if anyone cannot test their code in both versions then at least doing the following will help a lot

### Future imports
```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
```
This *must go at the beginning of the file* (comments do not count).
`__future__` forces some Python 3 standards on Python 2 code (see https://docs.python.org/2/library/__future__.html). The four above are the only ones that weren't enforced until Python 3.0 (see link), so they are the only ones necessary when using 2.7. Follow the links in that page to see why each of them. **TLDR:** always have `absolute_import` and `print_function`, and `division` whenever you have any math; `unicode_literals` is a little obscure and can cause trouble with the setup script, you'll have to figure out when it's necessary. This `__future__` import is silent in Python 3.

Note that you can use parentheses in `import` statements like you do in functions, which means you do not need a backslash to continue in the following line.

### String types
There were some changes in python 3 regarding the distinction between `bytes` and `str` (see `unicode_literals` above), and the generic `basestring` in Python 2 no longer exists in Python 3. Use `six.string_types` to cover all possibilities. For instance:
```python
import six
print(isinstance('a string', six.string_types))
```
Note the print syntax, with parenthesis: this is what `print_function` above enforces.

### Removed functions
```python
import sys

if sys.version_info[0] == 2:
    range = xrange
    from itertools import izip as zip
```
At least these are the two that I usually run into. In Python 2, `range` is a list as well as the built-in `zip`, but `xrange` and `izip` (from the `itertools` package) are generators. The former two are now generators in Python 3, while the latter two do not exist. Note also the `if` statement there: `sys.version_info` returns a list with each number in the version of Python being used (for instance, `[3,7,0]`).

**Comment by aimalz** [comment]
@cristobal-sifon We're marking this as an enhancement for now in favor of making `clmm` explicitly for Python 3 without support for Python 2.  We can work on compatibility after the hack week if there's interest.
