### ISSUE TITLE
Check/update the online documentation

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#290]
Title says it all. Check documentation [here](http://lsstdesc.org/CLMM/). In particular:
- the `installation` section is out-of-date and need updating
- we probably need a "Contact/Support" section.
- ~~resolve formatting when displaying tables in the notebooks~~(solved in #332 )
- ~~I'm not sure of the difference between the examples and the demo section and what should live where. Also not all the example notebooks are propagated to the docs. Should decide what is useful or not for the docs.~~(This last point is now being taken care of in #332 )

**Comment by hsinfan1996** [comment]
On the bottom of the documentation pages, is "Copyright 2018-2019" correct?

**Comment by combet** [comment]
The remaining points in this issue are overlapping with #289. I'll close this issue and copy the remaining points in #289.
