### ISSUE TITLE
Units: Mpc (not comoving), Msun - Remove h in modeling, mock data and notebooks

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#292]
Our data module work in physical units while modeling (and mock data) have Mpc/h and Msun/h. We agreed to move all to physical units for our function calls. This will also simplify/clarify the fitting examples notebooks where we had to correct "by hand" the h factor. Definite source of error.

Also, modeling returns density and surface density with `pc-3` or `pc-2`. I suggest returning `Mpc-3` and `Mpc-2` for consistency with the radius argument, but maybe typical numbers will then be super small and it's best to keep pc?

I suggest doing so once #282, #284 and #304 are merged, i.e. when we're happy with everything else in the mock data and modeling modules. For some of this, we also need to wait clarifications on #293.

**Comment by vitenti** [comment]
That is a simple change in modeling but it will require an update in everything else (notebooks, unit tests, etc), so we must be careful to not leave anything behind.

**Comment by combet** [comment]
Agreed, this is what I'm suggesting this as a last step, once everything else is settled.

**Comment by combet** [comment]
OK, so looking at the code and where to remove `h`:
- Numcosmo default is to work with proper distances, physical units, no h. The h dependence has been inserted by hand in all functions of `numcosmo.py`. So I think all is needed is to remove all `h   = self.cosmo.h ()` and `h` everywhere we see them in `numcosom.py` and it should be OK.
- The same goes for `ccl.py`, where this time it's the operations involving `self.cosmo['h']` we need to get rid of. Note that CCL default is to operate in comoving distances, so we do need to keep the `a_cl` factors included in `ccl.py`
-  cluster-toolkit default is to work in comoving units, with `h`. We have a patch already in place (`_patch_comoving_coord_cluster_toolkit_rho_m`) to use proper distance instead. So we just need to multiply the results of the functions in `cluster_toolkit.py` by the right number of `h`.

**Comment by combet** [comment]
OK, so looking at the code and where to remove `h`:
- Numcosmo default is to work with proper distances, physical units, no h. The h dependence has been inserted by hand in all functions of `numcosmo.py`. So I think all is needed is to remove all `h   = self.cosmo.h ()` and `h` everywhere we see them in `numcosom.py` and it should be OK.
- The same goes for `ccl.py`, where this time it's the operations involving `self.cosmo['h']` we need to get rid of. Note that CCL default is to operate in comoving distances, so we do need to keep the `a_cl` factors included in `ccl.py`
-  cluster-toolkit default is to work in comoving units, with `h`. We have a patch already in place (`_patch_comoving_coord_cluster_toolkit_rho_m`) to use proper distance instead. So we just need to multiply the results of the functions in `cluster_toolkit.py` by the right number of `h`.

**Comment by pennalima** [comment]
Generate new catalogs for tests with no 'h'. @pennalima

**Comment by combet** [comment]
Lists of things to do:
- [ ] Remove occurences of `self.cosmo['h']` in `ccl.py`
- [ ] Remove occurences of `self.cosmo.h` in `numcosmo.py`
- [ ] Mutliply by the right number of `h` in `cluster_toolkit.py` (need to wait on the new cosmo object #293 to know how to call it)
- [ ] Remove 1e-12,1e-6 factors in `numcosmo.py` to switch to Mpc units
- [ ] Remove 1e-12,1e-6 factors in `ccl.py` to switch to Mpc units
- [ ] Multiply by  1e12,1e6 factors to `cluster_toolkit.py` to switch to Mpc units
- [ ] Change units on all plots in the modeling demo 
- [ ] Propagate changes to mock_data.py

**Comment by vitenti** [comment]
We had to remove the occurences of h and updated units in the new CLMMCosmology object, so part of this issue was already fixed in branch issue/293/cosmology-object. pytest is working but Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb is failing. 

Now to create a cosmology object one must call:
```
mock_cosmo = modeling.Cosmology (H0 = 70.0, Omega_dm0 = 0.27 - 0.045, Omega_b0 = 0.045)
```
instead of 
```
mock_cosmo = FlatLambdaCDM(H0=70, Om0=0.27, Ob0=0.045)
```
However, even with this change, the example do not go through. Since the units are different I think that something must be broken in mock.

@combet, @marina-ricci

**Comment by combet** [comment]
@marina-ricci, @vitenti, continuing that conversaion in #293 as most of the unit conversion issues have been taken care of there.

**Comment by combet** [comment]
All of this is now being undertaken in #293.
