### ISSUE TITLE
Define a single CLMM cosmology format/object?

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#293]
We should have one clear CLMM cosmology format, that's independent of the modeling backend used. But the user should not have to do their own conversion using e.g. the `cclify_astropy_cosmo`, `astropyify_ccl_cosmo` functions.

These could be remain useful internally though. Need to check interaction with the updated modeling in #282.

**Comment by combet** [comment]
Below, comments from @vitenti  (originally in #300) but relevant to this issue:

"We need to decide how to deal with the cosmo object, currently it still acts as before (it is a simple dict or an astropy cosmology which is then converted to a simple dict). If we just extend the current solution and translate cosmo from ccl to a simple dict, then, the problem is that the cosmology object can be much more complicated: massive neutrinos, reionization, primordial cosmology parameters, etc, etc. Therefore, this conversion will end-up being very complicated.

I suggest that we implement for each backend a class that creates a simple cosmo object that will just encapsulate the cosmology object of that backend and provide a uniform access to the necessary methods (distances, H(z), etc, etc). That is, a simple interface that creates the cosmo from a small set of cosmological parameters, internally it instantiates the cosmology of the current backend in a consistent way. However, the final user can use the API of that backend to construct more complicated cosmology objects and then feed it to the simpler cosmo interface. By doing that we keep the simple approach possible and allow the user to use more complicated approaches if necessary."

**Comment by combet** [comment]
From what I've seen from the modeling backends
- cluster toolkit (CT) relies on astropy to compute the angular diameter distance between 2 redshifts. (we actually convert a CCL cosmo object into an astropy cosmo object to be able to call that function). So, for CT a natural cosmology object would be an astropy object.
- we need access to Omega_m to call the CT lensing function (so a `cosmo.get_h()` function?)
- we need access to `h` to remove it from the CT backend (so a `cosmo.get_Omegam()` function?)

**Comment by aimalz** [comment]
Thanks, everyone!  I mocked up a very basic superclass with subclasses for the three back-end cosmology objects [here](https://github.com/LSSTDESC/CLMM/blob/issue/293/cosmology-object/clmm/cosmo.py) -- now would be a good time to bring up any big problems.  So far, it covers only getting the two most universal parameters, no unit conversions yet, but I think that should be doable.

**Comment by combet** [comment]
I think it would be useful to have a method that generates a default cosmology, for a user-defined backend, e.g.
`my_cosmo = CLMMCosmology.default(backend)`, where `backend` would be `ct`, `nc` or `ccl` and  `my_cosmo` would then be an astropy cosmology object if `backend='ct'`, a NumCosmo object of `backend='nc'` and a CCL object if backend='ccl'.

**Comment by m-aguena** [comment]
@aimalz it might be more usefull to have a dictionary to store the cosmological parameters and get them using square brackets. This would allow us to add more parameters without having to touch the API. I can make this changes if you want

**Comment by vitenti** [comment]
Hello, @aimalz and @m-aguena I think it would be better to implement the methods: __getitem__, __setitem__, etc instead of having the parameters in two different places. I can implement the NumCosmo cosmo backend as an example if you like.

**Comment by m-aguena** [comment]
@vitenti yes, that is what I was trying to say

**Comment by m-aguena** [comment]
@aimalz @vitenti I updated the cosmology object with the gettitem/setitem methods

**Comment by combet** [comment]
Thanks for the heads up @sandro in #292. Switching the conversation to that thread as you've already taken care of most of the unit conversion in branch 293. Thanks a lot, that looks good! I've looked into the issue you mentioned on Example1.  (I've run with the CT backend):
- First, I replaced the `mock_cosmo = FlatLambdaCDM(H0=70, Om0=0.27, Ob0=0.045)` by `mock_cosmo = modeling.Cosmology (H0 = 70.0, Omega_dm0 = 0.27 - 0.045, Omega_b0 = 0.045)`
- Then, the first error encountered in the Example1 notebook comes from crazy `ra` values due to a Mpc to pc conversion in mock_data that should be removed. Easy fix.
- Then we run into another problem as we require a unit conversion, that makes use of `cosmo.angular_diameter_distance(redshift)` that is performed in utils.py, as @marina-ricci mentioned above. I could quickly fix it by defining a `def eval_da (self, z)` that returns `self.eval_da_z1z2(0,z)` in `clmm_cosmo.py`, and calling `cosmo.eval_da(z)` in `utils.py`. But we might want to define a eval_da(z) directly, without depending on eval_da_z1z2?
- The fitting procedure, that uses scipy `minimize` then fails for a reason I don't understand.
- However, with the same modifications as above, Example2 (that uses `curve_fit`) runs without problem and gives the right results (without the need to do r*cosmo['h'] for the fit as the data module and modeling modules now work in Mpc, no h, yeah!)

**Comment by combet** [comment]
@vitenti I've then switched to the `ccl` and `nc` backend for Example2, given that it was running successfully.
- No problem with the CCL backend
- Issue with the NC backend, where I ran into a `GObject descendants' instances are non-copyable` which occurs with  when `make_binned_profile` tries to add medata to the profile astropy (GCData) table.
Not sure what this is or how to fix this.

**Comment by combet** [comment]
@vitenti @marina I have not committed any of the changes I made above as I first want to double-check with you where to put those changes. I'd say we can continue in this branch until all is consistent. What do you think?

**Comment by m-aguena** [comment]
> Thanks for the heads up @sandro in [#292 (comment)](https://github.com/LSSTDESC/CLMM/issues/292#issuecomment-708111582). Switching the conversation to that thread as you've already taken care of most of the unit conversion in branch 293. Thanks a lot, that looks good! I've looked into the issue you mentioned on Example1. (I've run with the CT backend):
> 
> * First, I replaced the `mock_cosmo = FlatLambdaCDM(H0=70, Om0=0.27, Ob0=0.045)` by `mock_cosmo = modeling.Cosmology (H0 = 70.0, Omega_dm0 = 0.27 - 0.045, Omega_b0 = 0.045)` in the notebook
> * Then, the first error encountered in the Example1 notebook comes from crazy `ra` values due to a Mpc to pc conversion in mock_data that should be removed. Easy fix.
> * Then we run into another problem as we require a unit conversion, that makes use of `cosmo.angular_diameter_distance(redshift)` that is performed in utils.py, as @marina-ricci mentioned above. I could quickly fix it by defining a `def eval_da (self, z)` that returns `self.eval_da_z1z2(0,z)` in `clmm_cosmo.py`, and calling `cosmo.eval_da(z)` in `utils.py`. But we might want to define a eval_da(z) directly, without depending on eval_da_z1z2?
> * The fitting procedure, that uses scipy `minimize` then fails for a reason I don't understand.
> * However, with the same modifications as above, Example2 (that uses `curve_fit`) runs without problem and gives the right results (without the need to do r*cosmo['h'] for the fit as the data module and modeling modules now work in Mpc, no h, yeah!)

@combet I think we can just add a ˋeval_daˋ  in ˋclmm_cosmo.pyˋ that uses ˋeva_da_z1z2ˋ by default for now, and later create a ˋeval_daˋ in each individual backend.

**Comment by vitenti** [comment]
> > Thanks for the heads up @sandro in [#292 (comment)](https://github.com/LSSTDESC/CLMM/issues/292#issuecomment-708111582). Switching the conversation to that thread as you've already taken care of most of the unit conversion in branch 293. Thanks a lot, that looks good! I've looked into the issue you mentioned on Example1. (I've run with the CT backend):
> > 
> > * First, I replaced the `mock_cosmo = FlatLambdaCDM(H0=70, Om0=0.27, Ob0=0.045)` by `mock_cosmo = modeling.Cosmology (H0 = 70.0, Omega_dm0 = 0.27 - 0.045, Omega_b0 = 0.045)` in the notebook
> > * Then, the first error encountered in the Example1 notebook comes from crazy `ra` values due to a Mpc to pc conversion in mock_data that should be removed. Easy fix.
> > * Then we run into another problem as we require a unit conversion, that makes use of `cosmo.angular_diameter_distance(redshift)` that is performed in utils.py, as @marina-ricci mentioned above. I could quickly fix it by defining a `def eval_da (self, z)` that returns `self.eval_da_z1z2(0,z)` in `clmm_cosmo.py`, and calling `cosmo.eval_da(z)` in `utils.py`. But we might want to define a eval_da(z) directly, without depending on eval_da_z1z2?
> > * The fitting procedure, that uses scipy `minimize` then fails for a reason I don't understand.
> > * However, with the same modifications as above, Example2 (that uses `curve_fit`) runs without problem and gives the right results (without the need to do r*cosmo['h'] for the fit as the data module and modeling modules now work in Mpc, no h, yeah!)
> 
> @combet I think we can just add a ˋeval_daˋ in ˋclmm_cosmo.pyˋ that uses ˋeva_da_z1z2ˋ by default for now, and later create a ˋeval_daˋ in each individual backend.

@m-aguena Good idea, I'll add this implementation in the abstract class.

**Comment by m-aguena** [comment]
@vitenti I also think it would be a good idea to add `_get_z_from_a` and `get_a_from_z` to the abstract cosmology class. It does not require anything cosmology specific but I think it makes sense to have those there.

**Comment by vitenti** [comment]
@m-aguena Makes sense, I moved them to Cosmology, the tests and calls accordinly.

**Comment by combet** [comment]
Thanks @vitenti, @m-aguena! Ok if I proceed with the changes I mentioned above for mock_data, utils and the notebooks?

**Comment by vitenti** [comment]
@combet Yes go ahead, @pennalima and I are improving the tests and coverage.

**Comment by m-aguena** [comment]
@vitenti @combet does calling the cosmoloy object with `modeling.Cosmology` works? Do we want to keep this API? A direct call `clmm.Cosmology` might be more interesting

**Comment by m-aguena** [comment]
@combet yes, that is a simple implementation. In fact I just added it now. After an unrelated fix @vitenti is currently making, you should be able to import `clmm.Cosmology`

**Comment by vitenti** [comment]
@m-aguena @combet It should be working now.

**Comment by combet** [comment]
OK,
- mock_data.py updated to work with the new units
- utils.py updated with `eval_da` instead of `angular_diameter_distance`  and test_utils.py updated accordingly
- all notebooks run successfully and have been updated with the new cosmology update

Note that I created the cosmo objects throughout the notebooks and in test_utils with modeling.Cosmolgy as I could get clmm.Cosmolgy to work (might have had the wrong syntax, so went ahead with modeling.Cosmology instead)

For the moment, the old cosmo objects are just commented out - will remove those lines once we're happy with everything.

**Comment by vitenti** [comment]
@combet I just (hopefully) fixed the `GObject descendants' instances are non-copyable` error. It should work now. I tested here and it also worked when I used clmm.Cosmology (...).

**Comment by combet** [comment]
@vitenti, I confirm the `Gobject descendants` error is gone and using clmm.Cosmology worked as well (not sure what I did wrong yesterday). Anyway, all looks good! I won't have time today, but I will go through all the notebooks again and change the cosmo object instantiation to `clmm.Cosmology`

We can probably open a PR tomorrow? @vitenti  @m-aguena
