### ISSUE TITLE
nan to number

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CLMM#307]
Check the usage of numpy function nan_to_num. 
Do we need it? 
It can mask a "real" problem.

**Comment by m-aguena** [comment]
I agree with you that it could be dangerous, but the way it is implemented (specifying `nan=np.nan, posinf=np.inf, neginf=-np.inf`) it seems it will not be a problem. We should still check what happens when those values are used to fit the mass

**Comment by marina-ricci** [comment]
I think that's useless given the way it is written. But it's not dangerous neither.

**Comment by m-aguena** [comment]
@pennalima @marina-ricci I removed the use of `nan_to_num` since it wasn't doing anything and put a safeguard for possibly problematic values (z<0) on `eval_sigma_crit`.
