### ISSUE TITLE
Modifications in mock_data.py

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#309]
In `mock_data.py` there is an inconsistancy in  units in `_compute_ngals` : 

- ngals = density * field_size**2, with field_size in arcmin/h and density in gal/arcmin2. 

Some minor modifications in the docstrings : 
- "with a side length of 8 Mpc/h" > "with a default side length of 8 Mpc/h"
- "We draw physical x and y positions from uniform distribution with -4 and 4 Mpc" > "We draw physical x and y positions from uniform distribution within +- field_size "

**Comment by combet** [comment]
@marina This should now be fixed in the latest version, where units are homogenized throughout the code. See PR #311
