### ISSUE TITLE
Fake data generation

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#31]
Create fake (perfect) data catalog from known profile using either
- Parts of Doug's code (old clmassmod repo)
- Dallas' group tools
- Any other model tool...

**Comment by cavestruz** [comment]
This is done, yes?  @combet (Just looking to close some issues)

**Comment by combet** [comment]
There is a "perfect data generator" function in the test code for ShearAzimuthalAverager, but it should probably become a .py file by itself somewhere else. Also, I'd like to include a bit more to it, adding options for shape noise and source redshift distribution....

**Comment by combet** [comment]
A first mock data generator has been created and merged to master. Adding more flexibility to it is now performed under #67. Closing #66.
