### ISSUE TITLE
Names of modeling functions in the functional and OO interface

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#325]
Functions to predict lensing quantities do not have the same names when using the functional or the object-oriented interface. Need to decide on a consistent set of names to be implemented for v1.0.

**Comment by m-aguena** [comment]
FYI, those are the current names
```
Functional                        |  Object Oriented
---------------------------------------------------------
get_3d_density                    |  eval_density
predict_surface_density           |  eval_sigma
predict_excess_surface_density    |  eval_sigma_excess
get_critical_surface_density      |  eval_sigma_crit
predict_tangential_shear          |  eval_shear
predict_convergence               |  eval_convergence
predict_reduced_tangential_shear  |  eval_reduced_shear
predict_magnification             |  eval_magnification
```

**Comment by combet** [comment]
Thanks for the summary @m-aguena. I like the more explicit name of the functional interface (useful for people new to the field) and the more consistent and compact naming convention of the OO interface. So, as a first suggestion and to kick-start the discussion, I'll simply suggest a mixture of the two:
```
eval_3d_density
eval_surface_density
eval_excess_surface_density
eval_critical_surface_density
eval_tangential_shear
eval_convergence
eval_reduced_tangential_shear
eval_magnification
```

**Comment by vitenti** [comment]
I was thinking about the naming convention. I normally use eval (evaluate) to mean: given the object representing a model (here model can range from an actual model to a simple integrand) we can evaluate different aspects of it. So in short, eval means that the context is given by the object and you are going to just evaluate some quantity. In my opinion, "predict" is a little bit off, usually, it implies some kind of prediction given some data and that's not what it does. I would use "compute", meaning: given the input compute the value of something. 

I suggest the following:

- eval: used in methods to imply that it is an evaluation in the context of the object.
- compute: used in the functional interface informing that the computation depends only on the input parameter.

About the names themselves, we have two options, in the first (that we adopt in NumCosmo), we have in the documentation of each object an introduction where all quantities are discussed and defined, then the methods carry the names of the symbols used in this introduction. The second option is to avoid this split and put all documentation in each method, in this case, the method names should be more informative (as in the suggestion @combet gave above). I think that python module documentation usually follows the second approach. All in all, we should add a section to documentation explaining all these choices.

**Comment by combet** [comment]
Thanks @vitenti for clarifying the subtle difference between `eval` and `compute`, which makes sense. Using this, functional and OO interface won't share the same names, although the only difference would be the first word, and the difference is always the same, consistent and argued for.

Regarding the common part of the name, I'd tend to favour the second option (descriptive names + documentation in each methods/function) as it is then easy to guess what function needs to be used for what purpose, without the need to have the documentation open on the side and without prior knowledge of the code. That would mean something like:
```
Functional                        |  Object Oriented
---------------------------------------------------------
compute_density                   |  eval_density
compute_surface_density           |  eval_surface_density
compute_excess_surface_density    |  eval_excess_surface_density
compute_critical_surface_density  |  eval_critical_surface_density
compute_tangential_shear          |  eval_tangential_shear
compute_convergence               |  eval_convergence
compute_reduced_tangential_shear  |  eval_reduced_tangential_shear
compute_magnification             |  eval_magnification
```
