### ISSUE TITLE
Status of cluster-toolkit for v1.0?

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#327]
Interesting discussion at the last tag up. Putting that discussion here so we remember to discuss and keep a trace of that discussion

- @aguena first suggested to add a OO interface around CT so that all backends would have the same behaviour w.r.t to a functional and OO backend.
- That being said, @combet is a bit reluctant to have extra energy and time spent on CT, given that it may not be maintained anymore
To make a long discussion short:
- @aguena will inquire with DES folks whether CT is still being maintained or used.
- If not, @aimalz  suggested having a tagged release, e.g. v0.9 with all 3 backends as they are, and then to remove CT for v1.0. CCL and NC would keep both functional and object-oriented interfaces and we would have NC as the default backend the CLMM looks for in v1.0, given this is currently where we have most functionalities available. It would also make the description in the paper more straightforward.

If Michel learns that CT is still being maintained and used by DES, then it might be a good idea to keep it for v1.0, in which case have a OO layer around it could be useful.

**Comment by vitenti** [comment]
Hello @combet, I agree with you both (@m-aguena suggestion and your concern about CT future). The OO interface would be quite easy to implement, however, it will require our continued support in the future.

**Comment by combet** [comment]
Thanks @vitenti. So, if we do learn that CT is not maintained or used anymore in DES, would you be in favour of removing it from v1.0 (although we'd keep it in a tagged release 0.x, and mention all the cross-checks between CT, CCL and NC in the paper and/or DESC note)?

**Comment by m-aguena** [comment]
I talked to some DES people about it, and there is no concrete answer yet. Here is the main conclusions I got:

 - Since DES Y3 will have a likelihood that uses directly delta_sigma instead of masses, a specific project for cluster masses has not been created.
 - This likelihood currently uses cluster_toolkit, but I don't know if they will keep it. (I will investigate further.)
 - There is still some interest on having a project to measure the masses, but who will do it and how has not been decided yet.

**Comment by combet** [comment]
Thanks for looking into it @m-aguena. Looks like things are not quite clear cut yet and I am struggling weighing the pros and cons.

@vitenti and @m-aguena, calling out to your 'pipeline scientist' hat. What do you think would be the best course of action, still ensuring a v1.0 release before the holiday season. If we keep CT for v1.0, can a OO layer around it be implemented in that time frame? Also, I am not only concerned for this release but also for the future of CLMM, where we'll have to maintain and implement new functionalities to the modeling module (e.g., miscentering, 2-halo term - which are both available in CT, according to the documentation).

**Comment by m-aguena** [comment]
@combet after talking to DES people, it seems they are still using cluster_toolkit for the Y3 cosmology pipeline, but no one is in charge of maintaining it. They also told me they are open to suggestions. So I guess cluster_toolkit might not be used in the future.

Having said that, given the fact that there is currently some functionality exclusive to cluster_toolkit, I am incline to add the OO layer around it. I can dedicate some time and have it done for the v1.0 release.

**Comment by combet** [comment]
Thanks @m-aguena. OK, so let's proceed as you suggested, adding a OO layer around it so that CT has the same interfaces as CCL and NC in CLMM. I hadn't realised that CT was still in play in the Y3 analysis (even though not maintained).

**Comment by m-aguena** [comment]
Ok, I this implementation will be made in #330.
