### ISSUE TITLE
Remove the lsst/ directory from clmm/ for v1.0

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#329]
The a lsst/ directory contains a single file originally written to load DC2 quantities into a GalaxyCluster object, using GCRCatalogs. We haven't been using it anywhere or maintained it since it was written. The example notebooks show the user how to deal with DC2 data, without using that specific module. So I think we should simply remove the `lsst/` directory from `clmm/` for the v1.0 release.

**Comment by 96RadhikaJadhav** [comment]
Hi @combet Can I work on this issue?

**Comment by m-aguena** [comment]
@96RadhikaJadhav be our guest :+1:
