### ISSUE TITLE
Update and clean up example directory + update documentation

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#332]
- We need to review what notebooks to release with v1.0
- Can the names of the notebooks be made more explicit?

Items to be done

- [ ] rename notebooks
- [ ] remove obsolete notebooks
- [ ] add notebooks to the online documentation

**Comment by hsinfan1996** [comment]
- [ ] fix the unit in Example1

**Comment by hsinfan1996** [comment]
Maybe tell the users that they can change the backend with
```
import os
os.environ['CLMM_MODELING_BACKEND']='backend'
```
