### ISSUE TITLE
List of small things to correct 

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#340]
- [x] There is an error in the sign in the equation in the documentation of `get_tangentilal_component` in `dataops`.

gt = - (g1*cos() + g2*sin())

- [x]  #336 

- [x]   #337 

- [x] In `utils.py` : the documentation of `convert_units` specify that the cosmology should be an astropy object, but it is no longer the case.

**Comment by hsinfan1996** [comment]
- [ ] In `mock_data.py` line 92: field_size is optional

**Comment by combet** [comment]
- [ ] In the data_and_model_demo_DC2 notebook, there's still comment in cell 12 that says that modeling works in Msun/h, etc. The comment should be removed.
