### ISSUE TITLE
Decide the fate of lsst module

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#349]
There is some code on the lsst folder that we do not want for version 1.0. So it will be deleted from master, but it will be kept in a branch related to this issue so we can revisit it later.

**Comment by m-aguena** [comment]
A branch "[lsst module](https://github.com/LSSTDESC/CLMM/tree/issue/349/lsst_module)" was created to work on it.

**Comment by aimalz** [comment]
This has been dealt with already, so I'm closing the issue.
