### ISSUE TITLE
Add NC Example2 notebook (unbinned likelihood) to the examples

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#353]
@vitenti wrote a nice notebook in branch `issue/282/numcosmo_example`, starting from Example2 that shows how to perform an unbinned likelihood, fitting for both mass and concentration, using NC statistical framework.

It would be good to update it to the latest CLMM API and include more comment for the user to follow the NC-specific steps. Then, I think it would make a nice addition to our current set of examples that simply use `curve_fit`.

**Comment by pennalima** [comment]
@combet, we are working on it today.

**Comment by vitenti** [comment]
It's updated in `issue/353/numcosmo_examples` @pennalima will review and complete the documentation and it'll be ready for a PR.
