### ISSUE TITLE
Leftover code in numcosmo cosmology

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#356]
In the numcosmo cosmology class there is the function:

```
    def _init_from_params(self, H0, Omega_b0, Omega_dm0, Omega_k0):

        if not self.be_cosmo:
            self.be_cosmo = Nc.HICosmo.new_from_name(Nc.HICosmo, "NcHICosmoDEXcdm")
            self.be_cosmo.param_set_lower_bound(Nc.HICosmoDESParams.T_GAMMA0, 0.0)
            self.be_cosmo.omega_x2omega_k()
            self.be_cosmo.param_set_by_name("w", -1.0)
            self.be_cosmo.param_set_by_name("Tgamma0", 0.0)
        else:
            assert isinstance(cosmo, Nc.HICosmoDEXcdm)
            assert isinstance(cosmo.peek_reparam, Nc.HICosmoDEReparamOk)

        self.be_cosmo.param_set_by_name("H0", H0) 
        self.be_cosmo.param_set_by_name("Omegab", Omega_b0)
        self.be_cosmo.param_set_by_name("Omegac", Omega_dm0)
        self.be_cosmo.param_set_by_name("Omegak", Omega_k0)
```
@vitenti is this `if` really necessary? If so, there is a bug as `cosmo` was not defined.

**Comment by pennalima** [comment]
Hi @m-aguena,
"cosmo" appearing in 
assert isinstance(cosmo, Nc.HICosmoDEXcdm)
assert isinstance(cosmo.peek_reparam, Nc.HICosmoDEReparamOk)
 must be "self.be_cosmo".

**Comment by m-aguena** [comment]
@pennalima I see.

But is it necessary to have this piece of code there? From what I understood, the function `_init_from_params` is only called when `self.be_cosmo` is `None`. So it will never be used.

**Comment by vitenti** [comment]
@m-aguena Yes, it should be moved to _init_from_cosmo to replace:

```
assert isinstance(be_cosmo, Nc.HICosmo)
```
with:
```
assert isinstance(be_cosmo, Nc.HICosmoDEXcdm)
assert isinstance(be_cosmo.peek_reparam, Nc.HICosmoDEReparamOk)  
```

**Comment by m-aguena** [comment]
@vitenti thanks.

I can do this on branch #175 .

**Comment by m-aguena** [comment]
@vitenti when I added these `assert` there, I got an error on the tests:
```
>       assert isinstance(be_cosmo.peek_reparam, Nc.HICosmoDEReparamOk)
E       AssertionError
```

**Comment by vitenti** [comment]
Can you specify exactly in which test it fails? It looks like a bug...

**Comment by m-aguena** [comment]
@vitenti seems like all calls of this line failed:
https://github.com/LSSTDESC/CLMM/runs/1658120052

**Comment by vitenti** [comment]
Just fixed it, it was missing the parenthesis to indicate the function call.
