### ISSUE TITLE
DC2 examples: errors and warnings

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CLMM#358]
There are some warnings and errors when I try DC2 examples.

- [x] 'dc2_object_run2.1i_dr1' has been deprecated and may be removed in the future. Use dc2_object_run2.2i_dr3 instead.
not fully completed according to https://github.com/LSSTDESC/gcr-catalogs
- [x] TypeError: only dimensionless scalar quantities can be converted to Python scalars
resulted from H0 = dc2_cosmo.H0

**Comment by combet** [comment]
>     * [ ]  RuntimeWarning: divide by zero encountered in log10 return -2.5 * np.log10(flux) + AB_mag_zp_wrt_nanoJansky
> 
>     * [ ]  RuntimeWarning: invalid value encountered in sqrt

I think these two warning can be ignored.
