### ISSUE TITLE
pip-installed CCL v2.2.0 is now working on NERSC

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CLMM#375]
Before v2.2.0, pip-installed CCL cannot be found in virtual environments on NERSC. The Installation instructions suggest installing with conda from conda-forge. Now `pip install pyccl` is another choice and we could add it to INSTALL.md if we want to.

**Comment by aimalz** [comment]
I think it would be fine to go ahead and add this to the installation instructions if you feel so inclined @hsinfan1996.
