### ISSUE TITLE
Internal review round 1: quick/easy tasks

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#378]
First reviewer's comments:
- [x] Which CCL version do you use as back-end? (Same question for the other back-ends.)
- [x] Could you specify what type of documentation is available for CLMM? (I.e. readthedocs?)
- [x] In measuring the tangential shear, is there a cut in the redshift of the background galaxies? (There seems to be one mentioned around Eq. 23 but this wasn't clear to me - sorry if I missed it.)
- [x] Are boost factors measured/modeled by CLMM?
- [ ] Aside from the back-ends, are there other dependencies?
- [x] In section, it is described how galcat includes (ra,dec) for the clusters. With regards to the impact of miscentering, would it make sense to include different types of centers (e.g., coordinates of the BCG if available)? Or is it the expectation that the user would use a second instance of galcat for such purposes?
- [x] In line 594 you mention usage of the Chang et al. redshift distribution. This was replaced in the SRD by a more up-to-date one. It would be worth seeing whether it can be included.
- [x] Line 12: I think it would be appropriate to cite the DESC SRD here
- [x] Line 36 - Could you include some references?
- [x] Line 92 - I think it would be good to also refer to the KiDS cluster cosmology paper: https://arxiv.org/abs/2012.12273
- [x] Line 103 - typo "DESCwith"
- [ ] Line 181 - What is meant by mutual inconsistencies?
- [x] Line 206 - Can you clarify where are the constants taken from?
- [x] Line 352 - I think this is the first mention of magnification. Perhaps it would be worth introducing it at the top of Page 5.
- [x] Line 430 - Small typo: "takes" should be "take"
- [x] Table 3 seems to be referred to before Table 2 is mentioned

Second reviewer's comments:
- [x] Page 1, author list—there are some duplications that could be cleaned up.
- [x] Introduction: Lines 4-6: This sentence is awkwardly worded:  perhaps something like “During the first ten years of its, operations, the Rubin Observatory will perfom the Legacy Survey of Space and Time (LSST),…”
- [x] Section  3.2.1, after equation 13.  Are there any plans to introduce the possibility for asphericity, to simulate the signal from ellipsoids (or triaxial halos) as a function of their orientation?   
- [x] After equation 22.  It’s a little awkward to separate the discussion of analytic versus numerical solutions.   Might it be better talk about NFW vs/ Einasto here by moving the sentence on lines 386-388?
- [x] Section 3.2.2:  On line 414:  “may slightly differ” --> “may differ slightly”
- [x] Section 3.2.2:  Line 418:  “Doing so, we corss-checked”-->“We cross-checked”
- [x] Section 3.2.3:  Line 451:  “That way the methods” --> “This ensures that the methods”
- [x] Section 3.2.3:  Line 458: “differ just by the prefix”-->“differ only in the prefix”
- [x] Section 3.4, Line 498:  How does the GalaxyCluster object deal with merging clusters?
- [x] Section 3.4, Line 511, can the Galaxy attribute accommodate a p(z) array rather than a single number?
- [x] Section 3.4.3, line 572; typo:  “is” --> “if”
- [x] Section 3.5.1 line 582: “effects affecting”  Maybe pick a different wording?
- [x] Section 3.5.1 Starting at line 591 (or maybe the line above it).  You should highlight that these choices are default choices, and they can be changed (or will be able to be changed)
- [x] Section 4: Example suite:  Line 658 “rendered”-->”given”?
- [x] Section 5: future directions
- [x] Section 5.1, line 722:  “Beyond scales of”--> “On scales larger than
- [x] Section 5.1, Line 728. Reference to “it” is a bit vague.  Maybe use “this term”
- [x] Appendix a: Line 989:  “information of the” -->”information for the
- [x] Appendix a: Line 995: “and the source galaxies” --> “and the source galaxy objects need at least the following entries”

Third reviewer's comments:
- [x] page 3: line 202: are the angular diameter distances used to calculate sigma_crit not co-moving? (not a criticism, just most codes that I've seen that calculate luminosity and angular diameter distances return the co-moving distances, and formulas for computing sigma_crit found in most review articles assume co-moving distances)
- [x] page 4: given that the paper already refers the reader to review articles for the basics of weak lensing, most of page 4 seems superfluous. Many lensing concepts are introduced (such as magnification) that are not use anywhere else in the paper (except being referred to qualitatively in future directions and listed in a few tables with no dicussion). The only equation on this page that reader's really need is the definition of reduced shear (2) - the library doesn't try to extract g from shape measurements, so the rest of the details aren't really needed here. --> _Takeaway point: explicitly state pedagogical role of this content._
- [x] page 5: eqns 8 and 9: given this is to be used for LSST data in which the user can extract an arbitrarily large radius around a given point, how far out can one go and have these approximations still be reasonable?
- [x] eqns 11.5 (unlabeled): the g_x = 0 is only for a circular lens, one would expect <g_x> neq 0 if there is substructure in the cluster. so <g_x> = 0 is really only useful as a test for systematics in simulations where you start with a circular cluster model.

**Comment by combet** [comment]
All have been addresses. Paper has been resubmitted to IR. Closing issue.
