### ISSUE TITLE
Internal review round 1: Figure 1

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#379]
Reviewer 1 says `Figure 1: I think it would be useful to see more clearly in this figure what the inputs/outputs are.` --> Shall we include an additional flow chart of input/output as seen by a user?

Reviewer 2 says `Section 2: Figure 1 is a little hard to interpret, because the arrows are too thin.  I’d suggest making the connecting arrows thicker?` --> @m-aguena wrote the original tikz code so may know where the change has to be made.

**Comment by m-aguena** [comment]
@aimalz I made the arrows and lines thicker now.

**Comment by combet** [comment]
The point from reviewer 1 has been addressed as well. @m-aguena made a new flowchart highlighting the role of CLMM in a user-defined pipeline. Closing this issue.
