### ISSUE TITLE
Internal review round 1: Description of validation/tests

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#381]
Reviewer 1 says:

> Although some validation cases are presented, they don't feature very prominently. Would it be possible to highlight this more, incl. in the abstract? Perhaps by presenting a few plots from any of the validation tests? I think this is one of the selling points of such collaboration software tools. (For example, in the CCL paper we showed that our predictions for the observables met a certain requirement: they had intrinsic numerical errors that were smaller than the error bars expected from LSST. Section 3.2.2 seems to go in this direction but more details could be provided.)

Reviewer 2 says:

> On lines 421-425, where you cite the agreement between implementations, you should point out that the agreement is valid over a wide range in radii (as figure 2 shows)

Reviewer 3 says:

> page 7: line 420-425: the text states that all 3 codes agree at a the 10^-7 level - in what? is this the mass of a cluster measured from a radial shear profile for the same input data with the same concentration specified? some sum of absolute values of differences in shear across the profile? Figure 2 suggests this is the maximum difference between delta_Sigmas - if so, how does this integrate to an error on cluster mass?

--> @combet's figure of relative delta\_sigma difference and relative mass difference explains "If we want X% level of precision in mass, Y is what we need for delta\_sigma difference."  We should use these discrepancies across the model profiles to explain why we exclude CCL-EIN, etc.

--> Include explanation of reasoning for using Colossus of benchmark: CCL is ~1e-7, but numerical integration is not good enough where we have analytic NFW.  Colossus does everything numerically (very jagged), and agrees with everything including NC and analytical.

--> Suggested modifications to figure: state analytic vs. numerical in legend and/or separate panels for NFW and Einasto/Hernquist and/or recolor CCL analytic as baseline/reference to black

**Comment by combet** [comment]
Started addressing this question with 2 notebooks in branch `issue/381/validation_tests`.
- `examples/required_precision.ipynb` shows to which level we need the modeling to be accurate to be sensitive to a 1% mass change
- `examples/validation_tests.ipynb` shows the comparison of CCL, NC and CT, for NFW and Einasto. Highlights the fact that the numerical integration for CCL and CT do not reach the required level of precision.

In progress: @pennalima will check and include both numerical and analytical NFW profile for NumCosmo.

**Comment by pennalima** [comment]
Hi @combet , I included the numerical computations (NFW - NumCosmo).

**Comment by combet** [comment]
Thanks @pennalima. Updates:
- small changes to `examples/validation_tests.ipynb` for figure rendering in the paper
- addition of new `examples/mass_bias_from_models.ipynb` to address 3rd referee's comment on 'how does this integrate to an error on the mass'
