### ISSUE TITLE
Internal review round 1: Clarify scope

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#382]
Reviewer 1 says `My general impression of the paper is that it is geared towards presenting the CLMM functionalities and design choices, plus some example`

Reviewer 3 says:

> I'm somewhat confused on the purpose behind this paper - it reads as a mix of a basic review on cluster weak lensing methodology with some discussion of the implementation decisions in the software package, with a handful of examples of how to use the library added. There aren't enough details for this paper to serve as a manual, and there aren't enough discussions of validation tests performed and passed to assure the reader that the library is safe to use to obtain unbiased cluster mass measurements
> missing: Given that this paper is presenting a library to fit cluster mass profiles, there isn't any discussion of how well it does? You've given comparisons on how much agreement is between the various options, but nothing on an absolute measurement of how well you recover the input mass of a cluster from simulations. Figure 4 seems to show qualitatively that it basically works when using the right model, but providing some numbers for how well you recover the input masses for various models would be a good addition to the paper.

These comments indicate a need for more text reiterating the limited scope of the paper and reminding readers how each section fits into those goals.

**Comment by combet** [comment]
Done. Text changed accordingly. Paper resubmitted to IR. Closing issue.
