### ISSUE TITLE
Bug in mock data

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#386]
- line 243 of `mock_data.py`:
`z_source=galaxy_catalog['z']` should be `z_source=galaxy_catalog['ztrue']`

- line 213 should be: `prob = integrate.quad(z_distrib_func, zsrc_min, zsrc_max)[0]/norm`

I noticed this working on #335 and fixed it there.

**Comment by m-aguena** [comment]
@combet why am I assigned here? Is there anything else to do?

**Comment by combet** [comment]
Ooops, sorry @m-aguena, this was the wrong issue. Meant to assign you to the 'silent crash with CT' that we discussed during tag up today. Cheers
