### ISSUE TITLE
Add boost factor functionality

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#392]
Boost factors are used to "correct" the data vector from the contamination of cluster members. Feedback from the v1.0 paper is that boost factors would be a nice and easy functionality to add to the code base (not necessarily for v1.0 but at least in the near future). 

The power-law model (see the [CT documentation](https://cluster-toolkit.readthedocs.io/en/latest/source/boostfactors.html)) is very straightforward to implement. Note sure where to best include it though. It's a model, but it is used to correct the data... Maybe in `utils` for the time being?

**Comment by cavestruz** [comment]
- [ ] Filled out functions in `utils.py`:  
- [ ] Tests for these.
- [ ] demo in a notebook

**Comment by cavestruz** [comment]
Note:

- Tests started (mostly in stub form) in `test_utils.py`: 
- `test_compute_nfw_boost`
-  `test_compute_powerlaw_boost`
-  `test_correct_sigma_with_boost_values`
-  `test_correct_sigma_with_boost_model`

- **Previous Problem** with getting `np.nan_to_num` working with the default version of numpy in the tests.
