### ISSUE TITLE
Update theory prediction of g_t to account for a galaxy source distribution ?

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#397]
So far, the theory allows to predict the shear for a given source redshift (single source plane option). But we can use the overall redshift distribution of the sources to predict the corresponding shear, following:

See [WtGIII](https://arxiv.org/abs/1208.0605) (color-cut method).

![Screenshot 2021-05-25 at 10 10 37](https://user-images.githubusercontent.com/20227809/119462844-75189000-bd41-11eb-8a7e-e8cf698a3621.png)

where
![Screenshot 2021-05-25 at 11 35 00](https://user-images.githubusercontent.com/20227809/119475227-3ee10d80-bd4d-11eb-8422-43db63344db5.png)

An example of this was coded up in [this notebook](https://github.com/LSSTDESC/CLMM/blob/issue/335/nb_for_paper1.0/examples/Paper_v1.0/mass_bias_from_models.ipynb) for the v1.0 paper. But we should make this a proper option in the main code base.

This is linked to #130

**Comment by m-aguena** [comment]
I  think a way to implement this, and also prepare to use full pdf would be to pass different quantities with the argument `z_source`  depending on the value of `z_src_model` in `clmm.theory.compute_reduced_tangential_shear`. Something like

1. `z_src_model='single_plane'` -> `z_source`  is one single value representing all sources (float)
2. `z_src_model='radial_values'` -> `z_source`  is values of readshifs in each radial bin (array with same size of `r_proj`)
3. `z_src_model='weighing_the_giants'` -> `z_source` is the redshift of individual sources (array with size = n sources)
4. `z_src_model='weighing_the_giants_b'` -> `z_source`  is <beta_s> (float)
5. `z_src_model='photoz_pdf'` -> `z_source`  is the full photo-z pdf (2d array)

The code already can run cases 1 and 2, but the documentation is not expicit about it.

**Comment by shenmingfu** [comment]
I was about to ask whether we need to solve an effective `z_source` value from <beta_s> using (2), then I realized <beta_s^2> could give a different effective `z_source`. Maybe it's easier to use <beta_s> and <beta_s^2> as the inputs of the function?

**Comment by shenmingfu** [comment]
When I looked at the code structure, I realized the issue is a little more complicated than I thought. Should we try modifying the `def compute_reduced_tangential_shear(...)` in `CLMM/clmm/theory/func_layer.py`?

We can add 2 arguments: `beta_s_mean=None`, `beta_s_square_mean=None`. 
Then add `if z_src_model == 'weighing_the_giants_b':` like Michel mentioned.
Since this case is different from the `eval_reduced_tangential_shear` functions that are currently defined in the files in `clmm/theory/`, we can run these lines (similar to the functions defined in that file):
```
if beta_s_mean==None or beta_s_square_mean==None: 
    raise ValueError("beta_s_mean or beta_s_square_mean is not given.")

z_source = np.inf # or a very large number
gammat = gcm.eval_tangential_shear(r_proj, z_cluster, z_source)
kappa = gcm.eval_convergence(r_proj, z_cluster, z_source)
red_tangential_shear = beta_s_mean * gammat / (1. - beta_s_square_mean / beta_s_mean * kappa)
```

**Comment by marina-ricci** [comment]
@shenmingfu what is the status of that issue ?
