### ISSUE TITLE
Explore/understand better the differences between CCL and NumCosmo/Colossus

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#398]
For the profiles that need numerical integration (e.g., Einasto, Hernquist), the CCL out-of-the-box configuration does not provide the same level of accuracy as NumCosmo (which performs similarly to Colossus). This was first explored in [this notebook](https://github.com/LSSTDESC/CLMM/blob/issue/335/nb_for_paper1.0/examples/Paper_v1.0/validation_tests.ipynb).

It would be good to understand and see if CCL "precision parameters" could be changed to yield better agreement.

**Comment by hsinfan1996** [comment]
[](https://ccl.readthedocs.io/en/latest/api/pyccl.core.html)
As shown in the fourth note, parameters related to integration accuracy can be set. Not sure if they are the parameters we are looking for.

**Comment by combet** [comment]
See updated `validation_tests.ipynb` in branch `issue/398/ccl_precision`
