### ISSUE TITLE
Implement Einasto and Herquist profiles from CCL

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#402]
As shown in #398, it is possible to improve CCL's default integration to get enhanced precision, although, the results are quite sensitive to the choice of radial range and sampling. Once some configuration is agreed upon in #398, it should be implemented in CLMM.

**Comment by combet** [comment]
I've implemented the profiles in `ccl.py`, following the integration recipe of the `validation_test` NB of branch 398. I checked that the `demo_theory` notebooks (functional or OO) are running, asking `Einasto` or `Hernquist` from the CCL backend.

TODO:
- [ ] get benchmark file from NumCosmo for testing(@pennalima ?)
- [ ] Implement corresponding tests.

**Comment by combet** [comment]
This is also linked to #421

**Comment by pennalima** [comment]
Hi @combet, benchmarks are done.

**Comment by combet** [comment]
Hi @pennalima - thanks, but I don't see the new data files in the branch. Did you push those new files?

**Comment by pennalima** [comment]
Hi @combet, 
In branch "example_Einasto", you can see the files 
CLMM/tests/data/numcosmo/radial_profiles_einasto.txt (radial_profiles_hernquist.txt and config_einasto_henrquist_benchmarks.json).
