### ISSUE TITLE
Decide on a cosmology object to use

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#41]
We need to decide and implement which cosmology object that use (astropy/Colossus)

**Comment by cavestruz** [comment]
I would vote for astropy with the hope that colossus functionality is absorbed here **or**, did CCL also cover all of the functionality we'd need?  I think the initial plan was to port over colossus-specific functionality to CCL, contacting Benedikt in the process.  

Right now, there are a handful of places that use colossus:
tests/test_shear_azimuthal_averager.py
clmm/models/CLMM_densityModels_beforeConvertFromPerH.py
clmm/summarizer/data_and_model_demo.ipynb

and a few places that use astropy:
tests/test_shear_azimuthal_averager.py
clmm/summarizer/shear_azimuthal_averager_demo.ipynb
clmm/summarizer/shear_azimuthal_averager.py

**Comment by matthewwf2001** [comment]
I haven't worked with atsropy myself but I can work with Miyoung to change our cosmology dependencies to astropy if we need! However it is important to note that if we want to implement the DK profile we may need to use colossus. The DK profile can get extremely complicated if we wish to allow freedom in choosing the expression for the outer density term. For my work I use colossus for the DK density profile. If we don't use colossus then we may need to write the code for it from scratch.

**Comment by aimalz** [comment]
I talked with @tmcclintock today about CCL integration.  Perhaps he can give us a hand with evaluating the difficulty of each option?

**Comment by tmcclintock** [comment]
What do you need from astropy/colossus? Are you just looking for a modeling code to use for halo profiles?

**Comment by matthewwf2001** [comment]
We mainly use colossus for cosmology, like distances, h, etc. for a given or custom cosmology. I also use it for the DK halo profile (with flexibility for the outer profile).

**Comment by msimet** [comment]
I don't know about CCL, but for my own code, I use astropy for distances and colossus for models/concentrations.  I think astropy has a couple of benefits:
- It computes things in units, so you don't have to keep track, although you do have to do a little bookkeeping at the beginning and ending.
- It implements `d_A(z1, z2)`, which colossus does not currently do iirc (though I'm sure we could ask Benedikt).

Benefits of using colossus directly:
- You have to make a colossus cosmology object anyway if you want to use the modeling functions
- Without benchmarking, I think colossus is slightly faster because it doesn't do the integrals every time; however, if timing is an issue, you can write your own interpolation code (which is what I do when computing cross-correlations--I build a sigma crit interpolation table per cluster redshift at runtime).

**Comment by matthewkirby** [comment]
Since the discussion has shifted towards which code base we should use. I wanted to provide some more input. **Colossus is very slow**. I use colossus to compute concentration once (per step in a chain) in another project and when I profile my code, that single call is ~75% of my runtime (I am doing triple integrals as well...).

Recall that one of the end goals of this code base is to do heirarchical bayesian inference on clusters to measure masses without stacking. This is going to be very computationally expensive. Colosssus will be solid now since its already written, it works, and its easy to interface with but in the end, we are very likely going to need to come up with something faster. 

My thoughts are that we can write working code for the NFW profile. Once that is done, we can look at expanding to the Diemer profile and colossus/other options. Implementing these profiles into CCL (written in C) would provide a big speed increase and give us ease of mind that the code we use will be supported indefinitly (being a DESC product).

**Comment by msimet** [comment]
If you want a dict, you could just `LambdaCDM(**dict)` with astropy too. (I don't have a preference, just trying to give options!)

I'm slowly building up the public repo for [OffsetNFW](https://github.com/msimet/OffsetNFW), which does fast NFWs through high-fidelity interpolation tables or slower ones through direct evaluation, and includes miscentering and a bunch of lensing statistics. (I'm working on validating the precision of the tables right now for use cases other than the ones I've already used...or I will be once job application season ends.) I originally wrote that to optimize for MCMC codes, and could run a billion miscentered profile evaluations for ~20 radial points in 6 hours on a single core.  Might or might not be what you're looking for--and not a DESC product at the moment, though I am a DESC person.

**Comment by aimalz** [comment]
I take #84 and #103 as indicators that the decision has now been made and we know what to do next, so I'm closing this issue.
