### ISSUE TITLE
Example 1 returning an error

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#412]
I was running `Example1...` again today from the `master` branch and noticed the minimization procedure giving out an error `The user-provided objective function must return a scalar value`. I don't see what has changed, but this needs to be fixed before tagging v1.0! 
- [x] confirm this is reproducible by others
- [x] if so, fix it!

**Comment by combet** [comment]
Regarding the above, I see the same problem calling `scipy.optimize.minimize` directly instead of the wrapped version we have in `clmm`.

**Comment by combet** [comment]
OK, so I got the right behaviour back changing `sum` by `np.sum` in `def nfw_to_shear_profile(logm, profile_info)`.

Not sure if something as changed with the behaviour of the default non-numpy `sum()` function...

**Comment by hsinfan1996** [comment]
> OK, so I got the right behaviour back changing `sum` by `np.sum` in `def nfw_to_shear_profile(logm, profile_info)`.
> 
> Not sure if something as changed with the behaviour of the default non-numpy `sum()` function...

Did some quick check. The non-numpy sum() returns numpy.ndarray, while np.sum() returns numpy.float64.

**Comment by combet** [comment]
Thanks @hsinfan1996 - looking into the [documentation](https://docs.python.org/3/library/functions.html#sum), it does looks like the way `sum` worked has evolved between python 3.7 and 3.8. Anyhow, we do want the behaviour of `np.sum`, so I opened a PR with that change.

**Comment by hsinfan1996** [comment]
> Thanks @hsinfan1996 - looking into the [documentation](https://docs.python.org/3/library/functions.html#sum), it does look like the way `sum` worked has evolved between python 3.7 and 3.8. Anyhow, we do want the behaviour of `np.sum`, so I opened a PR with that change.

The PR looks good.
