### ISSUE TITLE
Changing alpha param in Einasto profile

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#421]
At the moment, the Einasto profile is implemented in CCL (an NumCosmo?) in a way that prevents the user of changing the `alpha` parameter (in CCL this is computed internally (using the parameterization of Diemer & Kravtsov (arXiv:1401.1216)). 

I would like to include the possibility of changing the `alpha` parameter.

**Comment by pennalima** [comment]
Hi @marina-ricci , in NumCosmo alpha is a parameter that can be fitted. For the moment, we do not consider any parametrization.

**Comment by marina-ricci** [comment]
To develop : 

1. A warning printing the "alpha" value in case of Einasto profile for CCL and NC (maybe not the same dfault value)
2. Develop the feasibility to fit extra parameter in CLMM

**Comment by combet** [comment]
Note - this is also linked to #402.

**Comment by marina-ricci** [comment]
@pennalima : You can check Fig. 13 in this paper [https://academic.oup.com/mnras/article/441/4/3359/1209689](Dutton & Maccio 2014) for reference on the physical rang for alpha. Also note that alpha and the concentration are negatively correlated.
