### ISSUE TITLE
Check tolerance in theory test

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/CLMM#453]
We need a tolerance quite high for the theory test to pass. We should investigate if we can do better than just increasing the tolerance value.

**Comment by vitenti** [comment]
@hsinfan1996 The tests are run with every back-end available in the running installation. In the tests functions you can find the modeling_data dictionary that contains all information in the current run, modeling_data['nick'] gives you the name of the current back-end.

I don't think we should just increase the tolerance. The best way to go is to investigate the source of divergence and fix (when possible) or if impossible to fix (e.g., inside CT) skip/increase tolerance only for those specific tests.

**Comment by hsinfan1996** [comment]
> @hsinfan1996 The tests are run with every back-end available in the running installation. In the tests functions you can find the modeling_data dictionary that contains all information in the current run, modeling_data['nick'] gives you the name of the current back-end.
> 
> I don't think we should just increase the tolerance. The best way to go is to investigate the source of divergence and fix (when possible) or if impossible to fix (e.g., inside CT) skip/increase tolerance only for those specific tests.

@vitenti Thank you for the explanation. Now I can see that all the installed backend are tested.
