### ISSUE TITLE
ceci for workflow management

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#46]
Later to do
- Reach out to @joezuntz and/or @EiffL who are working on Ceci

**Comment by cavestruz** [comment]
This is related to #1 , but perhaps not as much of a priority as other to-dos

**Comment by cavestruz** [comment]
Hi @joezuntz - thanks for the offer of help.  I *just* registered for the hack week.  As long as there are no bumps in travel plans, I will be there all week and currently plan to keep the entire time dedicated to pushing CLMM tasks along.  Perhaps hack week would be a good time for our team to interface with you to start the process of including CLMM in Ceci and make sure that the I/O and analysis parts of the code are structured appropriately.

**Comment by joezuntz** [comment]
@cavestruz - great, that sounds like a perfect sprint project.

**Comment by cavestruz** [comment]
Notes from quick chat with Joe: 

- Two options: either, (1) use a vanilla parsl, or (2) do what 3x2pt is doing, which is use ceci in order to isolate the science code from the workflow management tool (right now is parsl) in case we want to try other workflow management tools. Note: parsl *is* managed by some collaboration folks, so will likely be what is used in the long run.

- @m-aguena and I decided to use ceci.  Some documentation on ceci [here](https://ceci.readthedocs.io/).  Also, example integration of ceci at a pipeline stage [here](https://github.com/LSSTDESC/TXPipe/blob/master/txpipe/photoz.py).  

- Thought process for ceci instead of vanilla parsl:   While ceci may have a little bit more overhead in integration and constraints in pipeline (e.g. inputs and outputs should be relatively small number of files at each stage of output, and everything needs to be in one directory), but the restrictions force slightly simpler code structure.  Note, if we want to use parallelism, ceci is set up to run in MPI (and OpenMP).  

- Note, there is a tradeoff between defining little bits of pipeline stages where ceci is integrated into many .py files, and in large steps of the pipeline stages.  We're going to start with large steps of the pipeline stages.  Refering to our [diagram](https://github.com/LSSTDESC/CLMM/tree/master/clmm), one would go into the base class data (basic types); Models; and Inference Manager.  

- We will need to define input/output file formats (see [here](https://github.com/LSSTDESC/DESCFormats/blob/master/descformats/base.py) ), configuration options, synchronize processors if this is something that can/would be parallelized. 

- Can run ceci on pipeline filename (e.g. ceci <filename>.py); ceci takes in pipeline YAML files, one can specify the pipeline external inputs, the other config options.  See documentation on that [here](https://ceci.readthedocs.io/en/latest/config.html).

- List of all methods inherited from PipelineStage are [here](https://ceci.readthedocs.io/en/latest/stages.html)

**Comment by cavestruz** [comment]
Immediate low barrier steps to this issue: 
- pip install ceci and the cookiecutter template.
- Do an analogous ceci integration into GalaxyCluster (maybe?)

**Comment by m-aguena** [comment]
Screenshots of the whiteboard with many schematizations of how the pipeline/inferrer/manager should work [here](https://drive.google.com/file/d/1SqZd2V_j-rYpbZhJDLyXPAcA2H8ZmwEz/view?usp=sharing). Each page is the rearranging of the workflow from different days, so keeps the history of the development and the last page is what you should focus on.

**Comment by aimalz** [comment]
I think we've settled on clmm not being a pipeline in the same sense that, say, TXPipe is, because the user does the inference using clmm tools.  Does anyone want to keep this issue, or should we close it?

**Comment by cavestruz** [comment]
So, is the suggestion to *not* use ceci integration?

**Comment by aimalz** [comment]
@cavestruz I think that was what we concluded earlier in the week.  If CLMM encompassed the entire inference pipeline, then it might make sense, but the current scope of providing building blocks for users to flexibly make pipelines in scripts/notebooks of their own doesn't really need a workflow manager, at least not one that's part of CLMM.  Since there have not been any strong objections, I'm going to tentatively close this issue.
