### ISSUE TITLE
Mock cluster ensemble

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#462]
As we should soon have a `ClusterEnsemble` and the stacked analysis available (see PR #457 and #460), it would be good to update `mock_data` to be able to generate a mock cluster ensemble. Similarly to the `generate_galaxy_cluster` function, we could add a `generate_cluster_ensemble` function.

**Comment by nicolahunfeld** [comment]
I am working on it at the moment

**Comment by combet** [comment]
Hi @nicolahunfeld - thanks for the heads up! It would be good to discuss this with you in more details at one of our weekly Friday work/tag-up sessions.

(If you're planning to make this available in CLMM, please note that the procedure is first to open a corresponding issue and work in a branch named `issue/issue_number/short_description` so everyone can easily track what is going on, and avoid duplicating work.)

**Comment by nicolahunfeld** [comment]
Hi @combet. Sorry, I am really new to this. So shall I create a new Issue or just use this one? Unfortunately, I have to work on Fridays so I cannot attend the meetings most of the time. Is there one today at 3 pm CET? I could try to visit that.

**Comment by combet** [comment]
No worries @nicolahunfeld :) No need to create a new issue. We'll use this one

**Comment by marina-ricci** [comment]
Should be addressed by PR #457

**Comment by marina-ricci** [comment]
Should be addressed by PR #457

**Comment by marina-ricci** [comment]
To make it the most effective, we could have option to simulate the following : 

- cluster mass following mass function
- concentration following mass/concentration relation
- scatter in the concentration
- miscentering sampled from some distribution
- boost factors sampled from some distribution
- for Delta sigma, add the 2 halo term (with scatter?)
