### ISSUE TITLE
Converting SOD masses to another definition (ex: from 200m to 500c)

### ISSUE THREAD

**Issue by payerne** [LSSTDESC/CLMM#470]
Create module that allows the user to switch from a SOD definition to another (to be complementary to other codes providing mass-concentration relations with different SOD definition(s) than CLMM). [Here](https://github.com/payerne/DC2Analysis/blob/main/examples/Example_Conversion_from_200m_to_500c_NFW.ipynb) is an example notebook with a conversion of NFW mass and concentration from 200m to 500c, based on explanations and equations [here](https://www.overleaf.com/4353595172ndyyymnytxjn).

**Comment by hsinfan1996** [comment]
Great. I have been waiting for this, but since we do not have this functionality in CLMM, I wrote something similar to the functions shown in the notebook. What I wrote uses pyccl, so I hope it will be quick to implement the same functionalities for the CCL backend.

For CCL
```
import pyccl as ccl
#cosmo_astropy = FlatLambdaCDM(H0=71.0, Om0=0.265, Ob0 = 0.0448)
cosmo_ccl = ccl.core.Cosmology(h=0.71, Omega_c = 0.265-0.0448, Omega_b = 0.0448, Omega_k = 0.0)
cosmo = clmm.cosmology.ccl.CCLCosmology(be_cosmo=cosmo_ccl)

if rho_bgd = 'mean': alpha = cosmo.get_Omega_m(z)
rho_critical = cosmo_ccl.rho_x(cosmo.get_a_from_z(z), 'critical', is_comoving=False) # in Msun / Mpc^3
```

**Comment by hsinfan1996** [comment]
For NumCosmo
alpha = cosmo_nc.E2Omega_m(z)/cosmo_nc.E2(z)
rho_critical = Ncm.C.crit_mass_density_h2_solar_mass_Mpc3()*cosmo_nc.h()**2

**Comment by payerne** [comment]
@hsinfan1996, I created the branch [issue/470/mass_conversion](https://github.com/LSSTDESC/CLMM/tree/issue/470%2Fmass_conversion) for this topic.

**Comment by hsinfan1996** [comment]
> @hsinfan1996, I created the branch [issue/470/mass_conversion](https://github.com/LSSTDESC/CLMM/tree/issue/470%2Fmass_conversion) for this topic.

@payerne Thank you. I will finish the part that depends on cosmology and the backends.
