### ISSUE TITLE
Write init docstrings for each submodule so it is clearer what goes in there

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#48]
- [ ] Put this in the docstring for the __init__.py

- [ ] summarizers : straightforward operations to data, for which we would not fit free parameters (e.g. bin ends)

- [ ] models : things with (potentially) free parameters that can be fit (things you might want to fit/sample over for - might want to fit for M-c relation as an example.  fixed c=4 is a model under this definition.)

- [ ]

**Comment by cavestruz** [comment]
init for models in this issue is merged into #16

**Comment by aimalz** [comment]
The files in question no longer exist in the working branch for #112, so this issue is no longer relevant.  From now on, files that don't adhere to the style guide should not pass review in a PR.

**Comment by matthewkirby** [comment]
Following closing the issue, we are also deleting the branch for this issue since it is no longer relevant. 

@mchoi8739 this was your branch, we still value your work! If you wish to continue your involvement we should look at more up to date issues.
