### ISSUE TITLE
Failures in pytest caused by backend lookup

### ISSUE THREAD

**Issue by AngusWright** [LSSTDESC/CLMM#489]
Currently the pytest returns "failure"s for a number of tests, which we have traced to being caused by the incorrect interpretation of the [backend_is_available](https://github.com/LSSTDESC/CLMM/blob/c2569e6fcaaa2b187108166770f6d45be11d13af/clmm/theory/__init__.py#L67-L71) function in [conftest.py](https://github.com/LSSTDESC/CLMM/blob/c2569e6fcaaa2b187108166770f6d45be11d13af/tests/conftest.py#L18-L22). 

This is a simple fix, to correctly interpret the the results of `backend_is_available` as either: 

- Not a valid backend ("nonexist==True") 
- A valid, but unavailable backend ("avail==False")
- A valid and available backend ("avail==True") 

I've made a change to this effect in a local branch, that I can push. Example code from an updated conftest.py below:

```
  14 def modeling_data(request):
 15     param = request.param
 16     nonexist = False
 17
 18     try:
 19         avail = clmm.theory.backend_is_available(param['nick'])
 20     except ValueError:
 21         avail = False
 22         nonexist = True
 23
 24     if (nonexist):
 25         pytest.skip(f"Unsupported backend `{param}'.")
 26     elif (not avail):
 27         pytest.skip(f"Backend not available `{param}'.")
 28
```

However the fix raises another (possibly more concerning) issue. Without this fix, pytest returns: 

> 7 failed, 91 passed, 18 skipped, 69 warnings

With the new fix, there are _way_ more skipped tests: 

> 44 passed, 72 skipped, 21 warnings

which makes sense, but begs the question: How did ~50 tests pass when their requested backend wasn't even available?!

**Comment by m-aguena** [comment]
There are some unit tests specifically to test if the code raises the right error when the backend is not available. I don't know if they amount to 50 though. Your solution might be skipping those too. I will take a look

**Comment by marina-ricci** [comment]
@AngusWright do you still encounter this problem?
