### ISSUE TITLE
Incosistent behavior of clmm.Cosmology.eval_da_z1z2

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CLMM#507]
When z1>z2, NC and CT backends output negative numbers, while CCL raises CCLError. CCL does not allow z1>z2 (a1<a2) in the c level code, so maybe we can set argmin=z1 in validate_argument for z2.

**Comment by marina-ricci** [comment]
Hi @hsinfan1996 ! Could you check if you can resolve issue #455 at the same time?

**Comment by hsinfan1996** [comment]
> Hi @hsinfan1996 ! Could you check if you can resolve issue #455 at the same time?

@marina-ricci I think it would be better to address issue #455 in a separate branch since adding warnings requires importing a new module.
