### ISSUE TITLE
Default value of concentration in CCL and NumCosmo

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#513]
@vitenti @pennalima , I believe you implemented the modeling backend for NumCosmo and CCL, right? Can you confirm my understanding of the implementation of `_set_halo_density_profile` for them? In NumCosmo for instance we have this piece:

```
            cur_cdelta = 0.0 
            cur_values = False
            if self.hdpm:
                cur_cdelta = self.hdpm.props.cDelta
                cur_log10_mdelta = self.hdpm.props.log10MDelta
                cur_values = True

            self.hdpm = self.hdpm_dict[halo_profile_model](
                self.mdef_dict[massdef], delta_mdef)
            if cur_values:
                self.hdpm.props.cDelta = cur_cdelta
                self.hdpm.props.log10MDelta = cur_log10_mdelta
```
Does it mean, when `self.hdpm` is set up, the actual value of the curvature is whatever is inside `self.hdpm`? I know we can set the value with `_set_concentration`, but I just wanted to confirm.

I believe the same thing is happening for CCL, right? And with the default value of `c=4`
```
            cur_cdelta = 0.0
            cur_values = False
            if self.hdpm:
                cur_cdelta = self.conc.c
                cur_values = True
    
            self.mdef = ccl.halos.MassDef(delta_mdef, self.mdef_dict[massdef])
            self.conc = ccl.halos.ConcentrationConstant(c=4.0, mdef=self.mdef)
            self.mdef.concentration = self.conc
            self.hdpm = self.hdpm_dict[halo_profile_model](
                self.conc, **self.hdpm_opts[halo_profile_model])
            if cur_values:
                self.conc.c = cur_cdelta
            self.hdpm.update_precision_fftlog(padding_lo_fftlog=1e-4,
                                              padding_hi_fftlog=1e3
                                             )
```

I spotted this while working on PR #473 , and intend to make the concentration and delta_mdef to be explicit attributes of the modeling object. Additionally, I noticed that, as `self.delta_mdef` is not being set up in these functions, they are always passing the initial condition:

```
        if not ((halo_profile_model==self.halo_profile_model)
                and (massdef == self.massdef)
                and (delta_mdef == self.delta_mdef)):
```
I just want to make sure I understand it correctly befor making changes.

**Comment by vitenti** [comment]
Yes, that's exactly it, if there is no halo profile it just creates a new one with default values, but if there is already one there it first saves the current parameter values, create a new one and assign the values to the newly created.  

We have separated concentration and `delta_mdef` from the modeling object since they can be recreated without changing the CCL/NumCosmo objects. If you intend to tie down all objects that will add an extra cost when changing only, let's say, the concentration. That may have an impact when performing a MCMC with a fast/slow algorithm or fitting only the profile parameters.

**Comment by m-aguena** [comment]
I see... I still think we could have global `mdelta` and `cdelta` attribures in `Modeling`, and just update `hdpm` when `halo_profile_model`, `massdef` or `delta_mdef` is changed. Would that introduce any problems?
