### ISSUE TITLE
Bugs in notebooks during site building

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#515]
When trying to build the html files for the website I encountered a couple of error related to the notebooks. They were caused by:

- [x]  exclamation point at the end of warning - found in `demo_generate_mock_cluster.ipynb`, `demo_theory_functionality.ipynb` and `demo_mass_conversion.ipynb`
- [x] degree symbol - found in `Example1_Fit_shear_profile_with_miscentering.ipynb`

**Comment by hsinfan1996** [comment]
In `demo_mass_conversion.ipynb`, the problematic warnings are from CCL. I can suppress the warnings with `warnings.filterwarnings("ignore", module='(pyccl).*')` if that is what we want.

**Comment by m-aguena** [comment]
Yes, I think the best approach for CCL warnings is to suppress them. Actually, I think all problematic warnings are coming from CCL
