### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#546]
- [x] Update CLMM leads/contact info

**Comment by m-aguena** [comment]
@cavestruz whose info has to be updated?

**Comment by cavestruz** [comment]
@m-aguena Sorry, wrote this in a rush (noticed when I was showcasing to a collaborator CLMM as a well-structured code):
![image](https://user-images.githubusercontent.com/4805499/199733542-aa4b77a8-1c85-4387-90b5-c2cb54f536f5.png)
Celine's info needs to swap for yours.
