### ISSUE TITLE
Improve the 2 halo functions

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#552]
Current 2h functions (`eval_surface_density_2h`, `eval_excess_surface_density_2h` and their `_*` counterparts), have an inefficient integration scheme and also hardcoded values for the integrals. Should be improved.

**Comment by hsinfan1996** [comment]
Can you point out which lines are the slowest? My guesses are line 194 and line 213 in `theory/parent_class.py` because `simps` is slow.

**Comment by rancesol** [comment]
Hi @m-aguena, I've improved the performance of the `*_2h` functions as much as I can. After the initial call to the `eval_da` and `eval_linear_matter_powerspectrum` functions it was the `interp1d` function that was taking the most time. `splrep` in conjunction with `splev` runs twice as fast as `interp1d` with deviations below the 1e-12 % level. In the integration side, `simps` is slightly outperformed by `trapezoid` with deviations below the 0.05% level. I will implement these changes.

For the hardcoded values: were you thinking of just having for example the integration bounds made into optional function parameters?

**Comment by m-aguena** [comment]
Thanks @rancesol! The replacement for `interp1d` sounds really great. Replacing `simps` also seems interesting, but I would like to have a wider discussion with the group to see how the 0.05% deviation fits in our current precision.

For the hardcoded values: yes, I would put them into the arguments of the function.

Do you know how to create a branch and a pull request? You could make one with your changes.

**Comment by rancesol** [comment]
Yes, I have a branch and am now implementing the changes. I will keep `simps` until a decision is made but I will continue with the other changes.
