### ISSUE TITLE
Check if astropy has been updated before releasing numpy version fix

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#556]
The latest version of numpy 1.24.0 on conda-forge breaks astropy (see PR #553 ). There is a new version of astropy that fixes it but the new mirror has not been created, Check this  before releasing the numpy version in clmm's requirements.

**Comment by hsinfan1996** [comment]
https://github.com/LSSTDESC/CLMM/blob/5c848797e626e5edc49ba56b61e05088219879d0/tests/test_dataops.py#L422
This line fixes Numpy 1.24. I thought the problem was from Astropy.
