### ISSUE TITLE
Bug in generate mock cluster when there is shape noise and pdz

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#580]
There is a bug when the arguments of  `generate_galaxy_catalog` include:

```
shapenoise!=None,
photoz_sigma_unscaled!=None,
pzpdf_type='shared_bins'
```

(The replacement data is not generated with the same size of pdz!)

**Comment by combet** [comment]
Wow, nice catch @m-aguena! I reproduced the problem by pushing shapenoise to higher valies. Didn't encounter it with the values we have in the notebooks, so I missed it when reviewing the previous PR.
