### ISSUE TITLE
Remove recomputing of vectorization in NumCosmo backend

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#583]
There are many functions in the `NumCosmo` backend that vectorize internal functions at every call. That can be improved.

**Comment by hsinfan1996** [comment]
What functions specifically? Those in theory/numcosmo.py need np.vectorize

**Comment by m-aguena** [comment]
> What functions specifically? Most of those (if not all) in `theory/numcosmo.py` and `cosmology/ccl.py` need np.vectorize.

Yes, but they do not have to be "revectorized" every time we call them. I just created a PR draft with a possible solution
