### ISSUE TITLE
Argument error_model not being used in make_radial_profile

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#586]
The `dataops` function `make_radial_profile` has an `error_model` argument but is not being used

**Comment by sjdex** [comment]
Argument needs to be removed from definition and references if I am correct.? Can you assign me this one.

**Comment by m-aguena** [comment]
Actually, we want to have `error_model` being used inside `make_radial_profile`.

**Comment by hsinfan1996** [comment]
Right now the default is 'ste' and the other option 'std' is not supported.

**Comment by m-aguena** [comment]
> Right now the default option is 'ste' in utils.py and the other option 'std' is not supported. Do we need to implement 'std' first?

We do have the other option implemented:
```
 if error_model == "ste":
     ...
elif error_model != "std":
    raise ....
```
This fails if it is not `std` or `ste`
