### ISSUE TITLE
NumCosmo v0.19 Compatibility

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CLMM#614]
Hi @vitenti
Is NumCosmo v0.19 (and 0.18) still compatible with CLMM? I ran pytest on CLMM and and got `AttributeError: type object 'HICosmo' has no attribute 'new_from_name'`.

**Comment by vitenti** [comment]
The error was due to the usage of a deprecated constructor (new_from_name), I just create a PR with the fix, please take a look.

**Comment by hsinfan1996** [comment]
@vitenti I was trying the two example notebooks and got `AttributeError: 'GaussGammaT' object has no attribute 'y'`, but I think an earlier version of NC have had this issue already. Can you also fix this?

**Comment by vitenti** [comment]
Just updated these two Examples in the same PR. Please tell me there is something else not working properly.

**Comment by hsinfan1996** [comment]
> Just updated these two Examples in the same PR. Please tell me there is something else not working properly.

Thank you. I would like to confirm that after those changes the minimum compatible version is v0.19.

**Comment by vitenti** [comment]
It is mostly compatible with earlier versions, however, it is safer to require 0.19 minimum.

**Comment by hsinfan1996** [comment]
> It is mostly compatible with earlier versions, however, it is safer to require 0.19 minimum.

Yes, I find CLMM itself is compatible with v0.15 and above, but the updated notebooks requires v0.19+.
