### ISSUE TITLE
setup needs automatic package finder

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#62]

**Comment by aimalz** [comment]
Was this also addressed by #61?

**Comment by matthewkirby** [comment]
I actually do not know what is meant by "automatic package finder". That PR didn't change the setup.py though so I doubt it.

**Comment by aimalz** [comment]
I think this might have been taken care of by #105 in that we now specify versions of each dependency.  @cavestruz Was there anything else you wanted to see to close this issue?

**Comment by aimalz** [comment]
We have concluded that this is now taken care of.
