### ISSUE TITLE
Check how (or if) radial bin edges are propagated to the cluster ensemble profile

### ISSUE THREAD

**Issue by combet** [LSSTDESC/CLMM#628]
Currently it seems we have the bin edges information for single profile but this information seems to be lost when saving the individual profiles in the cluster ensemble. Need to look into it.

**Comment by hsinfan1996** [comment]
Only `"radius"` is there, and `"radius_min"` and `"radius_max"` are not, so yes, we lost the information on the bin edges.
Not sure if it is what you want, but adding `"radius_min"` and `"radius_max"` to `tbcols` in this line is a way to retain the bin edge info.
https://github.com/LSSTDESC/CLMM/blob/d1bf0a1be6b997fe8308c688bec2ba6c47f78c95/clmm/clusterensemble.py#L205

**Comment by m-aguena** [comment]
> Only `"radius"` is there, and `"radius_min"` and `"radius_max"` are not, so yes, we lost the information on the bin edges. Not sure if it is what you want, but adding `"radius_min"` and `"radius_max"` to `tbcols` in this line is a way to retain the bin edge info.
> 
> https://github.com/LSSTDESC/CLMM/blob/d1bf0a1be6b997fe8308c688bec2ba6c47f78c95/clmm/clusterensemble.py#L205

that is the exact idea here
