### ISSUE TITLE
Status of GCData object

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#65]
For reference, I am looking at the GCData and GCData_ objects in `clmm/core/datatypes.py`.

Just to jog memories:
GCData_: namedtuple. This was the object that was originally wanted
GCData: class that inherits GCData_. This is just to document the GCData_ object.

Looking in this file, we have the namedtuple, the class for documentation, then a whole bunch of functions that are exclusively for use with the GCData_ object. Why is this the correct implementation over just making GCData a class with all of these properties?

**Comment by aimalz** [comment]
@msimet reminds us that we can use a decorator on the methods that act on the GCData object to return the thing and only make it if it doesn't exist.

**Comment by matthewkirby** [comment]
Why are confirm_GCData, read_GCData, and write_GCData functions and not class methods?

**Comment by aimalz** [comment]
I don't recall what the reason was, if we ever had one (and, to the best of my admittedly limited knowledge, I don't think it affects @msimet's suggestion either way), but based on yesterday's discussions, I'm also in favor of making them class methods.  Any objections to changing the title and thus scope of this issue?

**Comment by matthewkirby** [comment]
We had a lengthy discussion of the GCData object and feel that each attribute of the GalaxyCluster object should be of type GCData as a hidden object with an underscore and then the main version is just a scalar. i.e. Cluster.ra would be a scalar and Cluster._ra would be a GCData. We also suggest some changes to GCData object.

- [ ] It should be immutable. Can we enforce this somehow?
- [ ] It should just be a class with attributes: source, definition, value, units. Two examples of how we think that this can be used
`GCData('sz miscentering dist', 'ra', 160.323, 'degrees')`
`GCData('redmapper', 'z', 0.304, None)`
These units are simply for bookkeeping and providence, we will not be converting between units.
- [ ] We should overload some functions for better behavior: printing? simple math?
- [ ] Cluster attributes 
- [ ] There are some existing functions, lets move them to cluster methods.

**Comment by matthewkirby** [comment]
@aimalz @m-aguena @cavestruz  Reading my last comment, what does this accomplish for us rather than just using an astropy table of things or a numpy array? It seems like an overcomplication to me.

**Comment by cavestruz** [comment]
@matthewkirby - Just noticed this in my unreads.... 
I have no strong feelings with regards to GCData, astropy table, etc.  Has this been settled on? Or is this part of ongoing steps for #152 that is still open?

**Comment by cavestruz** [comment]
@combet and I are looking through v1.0 tasks.   Currently, https://github.com/LSSTDESC/CLMM/blob/master/clmm/gcdata.py is a series of placeholders.  Is this still for v1.0? @m-aguena @matthewkirby

**Comment by cavestruz** [comment]
From @m-aguena - everything is now astropy tables.  We can put a pin on this and v1.x this.

**Comment by m-aguena** [comment]
After today's tag-up the idea came up of just making GCData a object that is equal to an astropy table. This way we don't have to change how the functions in the code are dealing with the tables and still make sure it will be stable in case astropy changes its API or if we decide to move to another data format.
