### ISSUE TITLE
Flexibility in mock data redshift distribution

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#67]
Currently, mock data produced has all background galaxies have the same redshift.  Would be good to have a distribution option.  Modification needed in clmm/mock_data.py .  Perhaps the src_z could also take in an array representing the distribution(?)  Note: Tests will need to be added to account for this as well.

**Comment by matthewwf2001** [comment]
Miyoung and I looked through clmm/mock_data.py . Is line 81 (z_best = ...) the place where we would make the array of redshifts drawn from a pdf?

**Comment by combet** [comment]
@matthewwf2001, @mchoi8739, it's great if you already have some tools to available! I created a Issue/67/mock_flexibility branch to work on that.

And yes, the easiest probably is to replace `z_best` by the array drawn from a pdf.
 
Once you had a chance to do so, I'll add a key to the `config` dictionary to specify whether to draw redshifts from a distribution or to use the single redshift option (I started with the latter for simplicity). Also, I'll modify the (optional) photoz error to scale with (1+z) in the case of the distribution of redshifts (it's constant at the moment as z_src is constant).

**Comment by combet** [comment]
@matthewwf2001, @mchoi8739, I changed the `z_min` in the redshift distribution code so that only galaxies *behind* the cluster would be drawn. 

Mock data demo is now updated with an example using the redshift distribution. Do we want any more functionalities for the mock data at this stage? Otherwise, I think it can be closed and merged to master.

**Comment by cavestruz** [comment]
Hi all,

Awesome work!  Once we're happy that all functionalities are there - I
agree, a pull request to master would be great.

Best,
Camille

**Comment by combet** [comment]
PR went through in Jan 2019. Closing issue.
