### ISSUE TITLE
Generalized profile model

### ISSUE THREAD

**Issue by lbaumo** [LSSTDESC/CLMM#7]

**Comment by aimalz** [comment]
A profile object will need to have an attribute that _is_ its functional form, which can then be isolated in inference.

**Comment by cavestruz** [comment]
Need a profile object that interacts with external tools like CCL and uses the base class for Model

**Comment by aimalz** [comment]
This is taken care of in [cluster-toolkit](https://github.com/tmcclintock/cluster_toolkit).
