### ISSUE TITLE
Compatibility between manager and inferrer

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#70]
Need to prepare data from galaxy_cluster objects to give to the inferrer.  Also, need to prepare the inferrer output to give back to the galaxy_cluster objects.  This is related to #23 (merged) and #68 (needs to be relatively completed first).

**Comment by m-aguena** [comment]
Screenshots of the whiteboard with many schematizations of how the pipeline/inferrer/manager should work [here](https://drive.google.com/file/d/1SqZd2V_j-rYpbZhJDLyXPAcA2H8ZmwEz/view?usp=sharing). Each page is the rearranging of the workflow from different days, so keeps the history of the development and the last page is what you should focus on.

**Comment by aimalz** [comment]
Does #94 indeed address this issue?

**Comment by aimalz** [comment]
This is out of scope.
