### ISSUE TITLE
Epic: Mock Pipeline

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CLMM#77]
Most of the pieces for the pipeline are in (e.g. each module has top level definitions/stub-like functionality to mock use).  This would be a good time to create a mock run.py like pipeline to see how each piece talks to one another, and to delineate the stages of the pipeline for ceci integration as well.

**Comment by m-aguena** [comment]
Screenshots of the whiteboard with many schematizations of how the pipeline/inferrer/manager should work [here](https://drive.google.com/file/d/1SqZd2V_j-rYpbZhJDLyXPAcA2H8ZmwEz/view?usp=sharing). Each page is the rearranging of the workflow from different days, so keeps the history of the development and the last page is what you should focus on.

**Comment by cavestruz** [comment]
![image](https://user-images.githubusercontent.com/4805499/61615985-4e650c00-ac35-11e9-8f27-2934d4710dc4.png)

From Paris Hack Day 2019

**Comment by m-aguena** [comment]
@aimalz @combet in `demo-pipeline.ipynb` the likelihoods are being computed with `(sum(obs-theo))^2` instead of `sum((obs-theo)^2)`, overestimating the errors

**Comment by m-aguena** [comment]
> @aimalz @combet in `demo-pipeline.ipynb` the likelihoods are being computed with `(sum(obs-theo))^2` instead of `sum((obs-theo)^2)`, overestimating the errors

@vitenti just fixed it
