### ISSUE TITLE
GitHub and Travis helpers: add your names to the new labels

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#78]
Please add your name to the description of our new labels if you can volunteer to help with the quick issues that come up with our software development tools.

**Comment by msimet** [comment]
I don't seem to have write permission to this repo to add my name myself, but I am a possible source of help! (git somewhat more than Travis, but I've used both and debugged both.)

**Comment by matthewkirby** [comment]
I added your name to both!

**Comment by msimet** [comment]
Thanks!

**Comment by aimalz** [comment]
I think we're good on this one.  Thanks @matthewkirby and @msimet!
