### ISSUE TITLE
Colossus Dependency

### ISSUE THREAD

**Issue by matthewkirby** [LSSTDESC/CLMM#84]
We do not want a dependency on external software i.e. Colossus. This is because we cannot be sure that this code will be maintained ad infinitum (whereas we can be sure of this for code like CCL). I wanted to put a checklist of files that Colossus is included in to be sure we get it all.

- [x] requirements.txt
- [ ] clmm/models/CLMM_densityModels_beforeConvertFromPerH.py (This file is being fully supplanted by code being developed within CCL)

**Comment by matthewkirby** [comment]
With regard to the second checkbox: 
The code in this file are classes for different profiles. This code is in development in CCL. The file also contains the code to go from profile -> delta sigma which, at this time, is not planned to be implemented in CCL. I am currently working on adapting the code in this existing file, cleaning it up and removing the colossus requirement for the NFW profile. We should plan a discussion on the general case that needs numerical integrals.

**Comment by aimalz** [comment]
We took care of this in the branch for #112.
