### ISSUE TITLE
DC2 data ingestion

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#9]
Let's start a notebook that does the following:

1. Query a halo (or a few) from DC2 (cut on quality flags).
2. Convert its data into the CLMM format (which may change later).
3. Associate the true data (position, redshift, mass proxy) with a GalaxyCluster object.
4. Associate the observed data (galaxy shears and positions, true redshifts for now) with a different GalaxyCluster object.

**Comment by cavestruz** [comment]
Also connected to Issue #3

**Comment by cavestruz** [comment]
Closing this and making a new issue for:

4. Associate the observed data (galaxy shears and positions, true redshifts for now) with a different GalaxyCluster object.
