### ISSUE TITLE
Add informative functions in GalaxyCluster

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#93]
Add functions to display what is the content currently inside GalaxyCluster.

**Comment by aimalz** [comment]
Just to check that I understand the issue, is this about adding some metadata to the `GalaxyCluster` so it has something to give `Manager._ask`?  If so, I think we're ready to tackle this now that #92 has been addressed by PR #94.  (If not, @m-aguena, could you clarify here?)

**Comment by m-aguena** [comment]
@aimalz this is just to be able to use print function in the GalaxyCluster object and have something the user can read and understand.

**Comment by aimalz** [comment]
Thanks @m-aguena!  This also seems related to #65, in that class methods seem to be the solution in both cases.  Now it seems obvious from your original comment/title, but, to reiterate for my own poor memory later on, this issue can be closed when the GalaxyCluster class includes a method for printing some user-readable summary information.

**Comment by m-aguena** [comment]
@aimalz I think #65 is more related for internal use of the clmm package. This one would be for api. Check the `examples/run_function_on_GalaxyCluster.ipynb` notebook for an example.

**Comment by matthewkirby** [comment]
This issue can be closed when
- [ ] Merge refactored code
- [ ] add_data, remove_data, read, write, __str__, __repr__

**Comment by matthewkirby** [comment]
Just merged PR #145 which added the `__repr__` function (by default prnt=repr)

**Comment by matthewkirby** [comment]
Looking at my checklist of what is needed to close this issue, we have everything done except the add_data and remove_data. SIn the new framework, this is not something that we need to do. With that, I am going to close this issue and check off box in Issue #112
